(function(g){var window=this;var q1=function(a){var b={languageCode:a.l,languageName:a.o,displayName:g.gt(a),kind:a.A,name:a.B,id:a.Ga,is_servable:a.H,is_default:a.isDefault,is_translateable:a.F,vss_id:a.C};a.g&&(a=a.g,b.translationLanguage={languageCode:a.languageCode,languageName:a.languageName,languageOriginal:a.g,id:a.id,is_default:a.isDefault});return b},r1=function(a){return a.g?a.g.languageCode:a.l},Toa=function(a,b){var c=new g.ft;
c.l=a.l;c.o=a.o;c.B=a.B;c.A=a.A;c.isDefault=!1;c.F=a.F;c.C=a.C;c.G=a.G;c.g=b;return c},s1=function(a){if(!Uoa.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Voa,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=(0,window.parseInt)(a.substr(1),16);return[a>>16,a>>8&255,a&255]},Woa=function(){this.l=[];
this.g=[]},t1=function(a,b){return b?a.g.concat(a.l):a.g},u1=function(a,b){switch(b.A){case "asr":var c=a.l;
g.Ja(c,(0,g.z)(b.eq,b))||c.push(b);break;default:c=a.g,g.Ja(c,(0,g.z)(b.eq,b))||c.push(b)}},v1=function(a,b){g.G.call(this);
this.Bv=!!b;this.l=new Woa;this.C=[]},w1=function(a,b){v1.call(this,a,b.sl);
this.o=void 0;this.g=null;this.C=b.captionTranslationLanguages},x1=function(){this.Xa=[]},y1=function(a,b,c,d,e,f){g.G.call(this);
this.L=a;this.A=b;this.C=new x1;this.g=null;this.H=d;this.O=f;this.l=this.o=null;this.G=c;this.F=e||!1;this.J=new g.L(this.Tv,1E3,this);g.I(this,this.J);this.B=new g.Qq(this);g.I(this,this.B);g.Q(g.V(b).experiments,"html5_disable_captions_seek_complete")?this.B.M(b,"seekto",this.bx):this.B.M(b,"seekcomplete",this.MG);this.bx(b.ya());this.Tv()},z1=function(a,b){b-=g.AI(a.A);
var c=a.g;a.g=g.Ha(a.G.sf(b).g);c!=a.g&&a.O&&a.O()},A1=function(a,b){var c=g.Bw(b,a.L,{}).Jb(),d={format:"RAW",
withCredentials:!0};a.F&&(d.responseType="arraybuffer");a.l=g.aq(c,d,3,100).then((0,g.z)(a.pL,a));a.o=b;c=a.C;d=a.o.g[0].l;var e=g.Za(c.Xa,d);0<=e||0>e&&1==(-e-1)%2||(e=-e-1,0<e&&1==d-c.Xa[e-1]&&e<c.Xa.length&&1==c.Xa[e]-d?(g.Pa(c.Xa,e),g.Pa(c.Xa,e-1)):0<e&&1==d-c.Xa[e-1]?c.Xa[e-1]=d:e<c.Xa.length&&1==c.Xa[e]-d?c.Xa[e]=d:(g.Wa(c.Xa,e,0,d),g.Wa(c.Xa,e+1,0,d)))},B1=function(a,b){v1.call(this,g.V(b));
this.g=a;this.A=b;this.o=null;this.B=!1;this.F=g.uy(g.V(this.A))&&!this.g.l;this.G=g.Q(g.V(this.A).experiments,"web_player_enforce_format3_manifestless_captions_killswitch")},C1=function(a,b){var c=[],d;
for(d in a.g.g){var e=a.g.g[d];if(g.PP(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.ft({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Xoa=function(a,b){return null!=b&&b in a.g.g?a.g.g[b]:null},D1=function(a,b,c){var d=[],e;
for(e in a.g.g){var f=a.g.g[e];if(g.PP(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode==b&&d.push(f)}}return d.length?d[0]:null},E1=function(a,b,c,d,e){v1.call(this,e||null,d);
c=c||g.up(a).hl||"";c=c.split("_").join("-");this.B=g.wp(a,{hl:c});this.A=b;this.G={};this.g=null;this.o=void 0;this.F=!!e&&g.Q(e.experiments,"web_player_include_formats_in_tts_track_request_killswitch")},F1=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.cC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.o=f;this.l=k},G1=function(a,b,c,d,e){g.cC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.l=[]},I1=function(a){a=void 0===a?{}:a;
var b="_"+H1++;return new G1(0,0x8000000000000,0,b,a)},L1=function(a,b,c,d,e,f,k){var l={};
g.Fa(l,b);g.Fa(l,a.params);g.Fa(l,c);var m={};g.Fa(m,b.ib);a.params.ib&&g.Fa(m,a.params.ib);g.Fa(m,c.ib);l.ib=m;g.O.call(this,{D:"div",I:"caption-window",N:{id:"caption-window-"+a.id,dir:1==l.vg?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",I:"captions-text"}]});this.B=[];this.X=!1;this.A=a;this.G=[];this.J=[];this.Za=e;this.Wa=f;this.Oa=k;this.F=null;this.ha=.96*e;this.ua=.96*f;this.l=l;this.Ka=c;this.o=this.g["captions-text"];this.Ha=null!=this.o.style["box-decoration-break"]||
null!=this.o.style["-webkit-box-decoration-break"];this.ba=d/360*16;this.type=0;this.na=this.ba*J1(m);a=new g.Wq(this.element,!0);g.I(this,a);a.subscribe("dragstart",this.JG,this);a.subscribe("dragmove",this.IG,this);a.subscribe("dragend",this.HG,this);this.ra=this.pa=0;a="";this.l.windowOpacity&&(a=s1(this.l.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.l.windowOpacity+")");b={"background-color":a,display:!1===this.l.isVisible?"none":"","text-align":Yoa[this.l.textAlign]};this.Ha&&(b["border-radius"]=
a?this.na/8+"px":"");(this.C=g.Q(this.Oa,"web_player_vertical_captions")&&(2==this.A.params.vg||3==this.A.params.vg))&&K1(this,this.element);g.hh(this.element,b);switch(this.l.Rf){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},K1=function(a,b){var c="vertical-rl";
1==a.l.es&&(c="vertical-lr");g.rd&&(c="vertical-lr"==c?"tb-lr":"tb-rl");g.hh(b,"-o-writing-mode",c);g.hh(b,"-webkit-writing-mode",c);g.hh(b,"writing-mode",c);g.hh(b,"text-orientation","upright");3==a.A.params.vg&&(g.hh(b,"text-orientation",""),g.hh(b,"transform","rotate(180deg)"))},J1=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0==a.offset||2==a.offset)b*=.8;return b},M1=function(a,b){var c={},d=b.background?b.background:a.l.ib.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.l.ib.backgroundOpacity;d=s1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ha&&(c["box-decoration-break"]="clone",c["border-radius"]=a.na/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.ba*J1(b)+"px";d=1;e=b.color||a.l.ib.color;if(b.color||null!=b.textOpacity)e=s1(e),d=null==b.textOpacity?a.l.ib.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",c.color=
e,c.fill=e;var f=b.charEdgeStyle;0==f&&(f=null);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Vt&&(k=e=b.Vt);var l=a.ba/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),u=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=u;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+n+"px "+
e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.Op()?'"Carrois Gothic SC", sans-serif-smallcaps':
'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.l.ib.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7==b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.te&&(c["font-style"]="italic");b.underline&&(c["text-decoration"]="underline");
b.Yl&&(c.visibility="hidden");return c},N1=function(a,b,c){a.X=a.X||!!c;
var d={};g.Fa(d,a.l.ib);g.Fa(d,c||b.l);g.Fa(d,a.Ka.ib);c=a.G[0];if(c&&d.background==c.background&&d.backgroundOpacity==c.backgroundOpacity&&!!d.Yl==!!c.Yl&&d.charEdgeStyle==c.charEdgeStyle){var e;for(e=0;e<a.G.length;e++)if(g.Ub(d,a.G[e])){var f=a.J[e];break}if(!f){e={};for(var k in d)d[k]!=c[k]&&(e[k]=d[k]);f=g.xd("SPAN");g.hh(f,M1(a,e));a.J[0].appendChild(f);e=1}a.J.length=e;a.G.length=e}else a.J.length=0,a.G.length=0,f=g.xd("SPAN"),g.hh(f,M1(a,d)),a.o.appendChild(f);k=!d.Yl;e=(c=g.t(b.text))?b.text.split("\n"):
[b.text];for(var l=0;l<e.length;l++){var m=e[l];if(0<l||0==a.B.length||!b.o){if(0<l||0!=a.B.length){var n=g.xd("BR");f.appendChild(n)}k&&a.Yi(f)}m&&(k?a.F:f).appendChild(c?g.yd(m):m)}if(!c)for(k=b.text.querySelectorAll("RT".toString()),c=0;c<k.length;c++)g.hh(k[c],M1(a,d)),g.hh(k[c],"font-size","50%");a.G.push(d);a.J.push(f);a.B.push(b)},O1=function(){},Q1=function(){this.A=this.l=this.mode=this.o=0;
this.B=new P1(this);this.C=new P1(this);this.g=[];this.clear()},Zoa=function(a,b,c){if(255==a&&255==b||!a&&!b)return{kl:a,
ll:b,result:0};a=R1[a];b=R1[b];if(a&128){if(!(b&128)&&0!=c.g&&c.l==b)return{kl:a,ll:b,result:1}}else if(b&128&&1<=a&&31>=a)return{kl:a,ll:b,result:2};return{kl:a,ll:b,result:3}},$oa=function(a,b,c,d){255==b&&255==c||!b&&!c?(45==++a.A&&a.reset(),a.B.g.clear(),a.C.g.clear()):(a.A=0,S1(a.B,b,c,d))},apa=function(a,b){a.g.sort(function(a,b){var c=a.time-b.time;
return 0==c?a.order-b.order:c});
for(var c=0;c<a.g.length;c++){var d=a.g[c];a.l=d.time;0==d.type?$oa(a,d.Pt,d.Qt,b):1==d.type&&a.o&496&&S1(a.C,d.Pt,d.Qt,b)}a.g.length=0},T1=function(){this.g=0},U1=function(){this.l=this.o=this.g=0},V1=function(){this.timestamp=this.Rd=0},W1=function(a){this.o=[];
for(var b=0;15>=b;b++){this.o[b]=[];for(var c=0;32>=c;c++)this.o[b][c]=new V1}this.g=this.l=this.row=0;this.style=new T1;this.B=a;this.A=0},X1=function(a,b){if(3==a.style.g){for(var c=0,d=0,e=a.B.l+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var u=a.o[m][p];
if(0!=u.Rd){0==c&&(c=m,d=p);n=String.fromCharCode(u.Rd);var x=u.timestamp;x<e&&(e=x);u.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0==u.Rd||32==p)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.B(c,d,e,l,f)}else for(d=c=0,f=e=a.B.l+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(p=a.o[k][m],u=p.Rd,0!=u&&(0==c&&(c=k,d=m),n=String.fromCharCode(u),x=p.timestamp,x<=e&&(e=x),l+=n,p.reset()),32==m||0==u)l&&b.B(c,d,e,f,l),e=f,l="",d=c=0},fpa=function(a,b){switch(a){case 0:return bpa[(b&127)-32];
case 1:return cpa[b&15];case 2:return dpa[b&31];case 3:return epa[b&31]}return 0},Y1=function(a){return a.o[a.row][a.l]},Z1=function(a,b,c){2<=b&&1<a.l&&(--a.l,Y1(a).Rd=0);
var d=Y1(a);d.timestamp=a.B.l+0;d.Rd=fpa(b,c);32>a.l&&a.l++},$1=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++)a.o[b+e][f].Bl(a.o[c+e][f])},a2=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.o[b+d][e].reset()},b2=function(a){a.row=0<a.g?a.g:1;
a.l=1;a2(a,0,15)},c2=function(a){this.A=a;
this.B=0;this.style=new T1;this.C=new W1(a);this.F=new W1(a);this.G=new W1(a);this.l=this.C;this.o=this.F;this.g=this.l},d2=function(a,b,c){var d=a.l,e=!1;
switch(a.style.get()){case 4:if(0<d.g)break;case 1:case 2:X1(d,c),b2(a.l),b2(a.o),d.row=15,d.g=b,e=!0}a.style.set(3);a.g=d;a.g.style=a.style;a.A.mode=1<<d.A;e?d.l=1:d.g!=b&&(d.g>b?(X1(d,c),a2(d,d.row-d.g,b)):d.row<b&&(b=d.g),d.g=b)},e2=function(a){a.style.set(1);
a.g=a.o;a.g.g=0;a.g.style=a.style;a.A.mode=1<<a.g.A},f2=function(a){a.style.set(4);
a.g=a.G;a.g.style=a.style;a.A.mode=1<<a.g.A},P1=function(a){this.l=a;
this.g=new U1;this.B=0;this.o=new c2(a);this.C=new c2(a);this.A=this.o},S1=function(a,b,c,d){a.g.update();
b=Zoa(b,c,a.g);switch(b.result){case 0:return;case 1:case 2:return}var e=b.kl;c=b.ll;if(32<=e||!e)a.l.mode&a.l.o&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.A.g,b&96&&Z1(a,0,b),c&96&&Z1(a,0,c),0!=b&&0!=c&&3==a.style.g&&X1(a,d));else if(e&16)a:if(!a.g.matches(e,c)&&(b=a.g,b.o=e,b.l=c,b.g=2,b=e&8?a.C:a.o,a.A=b,a.l.mode=1<<(a.B<<2)+(b.B<<1)+(4==b.style.g?1:0),(a.l.mode|1<<(a.B<<2)+(b.B<<1)+(4!=b.style.g?1:0))&a.l.o))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];a=c&16?4*((c&14)>>1):
0;c=b.g;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!=c.row){if(d<c.g&&(d=c.g,d==c.row))break;var f=1+c.row-c.g,k=1+d-c.g;$1(c,k,f,c.g);b=f;e=c.g;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));a2(c,b,e)}}c.row=d;c.l=a+1}else switch(e&7){case 1:switch(c&112){case 32:Z1(b.g,0,32);break a;case 48:57==c?(b=b.g,Y1(b).Rd=0,32>b.l&&b.l++):Z1(b.g,1,c&15)}break;case 2:c&32&&Z1(b.g,2,c&31);break;case 3:c&32&&Z1(b.g,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:e2(b);break;case 33:b=
b.g;1<b.l&&(--b.l,Y1(b).Rd=0);break;case 36:b=b.g;d=Y1(b);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(b.o[a][c]==d){for(;32>=c;c++)b.o[a][c].reset();break}break;case 37:d2(b,2,d);break;case 38:d2(b,3,d);break;case 39:d2(b,4,d);break;case 40:Z1(b.g,0,32);break;case 41:b.style.set(2);b.g=b.l;b.g.g=0;b.g.style=b.style;b.A.mode=1<<b.g.A;break;case 42:d=b.G;d.g=15;d.style.set(4);b2(d);f2(b);break;case 43:f2(b);break;case 44:a=b.l;switch(b.style.get()){case 1:case 2:case 3:X1(a,d)}a2(a,0,15);break;case 45:b:{a=
b.g;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.l=1;break b}case 3:}2>a.g&&(a.g=2,a.row<a.g&&(a.row=a.g));b=a.row-a.g+1;X1(a,d);$1(a,b,b+1,a.g-1);a2(a,a.row,1)}break;case 46:a2(b.o,0,15);break;case 47:X1(b.l,d);d=b.o;a=b.A.l+0;for(c=1;15>=c;++c)for(e=1;32>=e;++e)d.o[c][e].timestamp=a;d=b.o;b.o=b.l;b.l=d;e2(b)}break;case 7:switch(c){case 33:case 34:case 35:b=b.g,32<(b.l+=c&3)&&(b.l=32)}}},g2=function(a){g.G.apply(this,arguments)},h2=function(a){g2.call(this);
this.l=a;this.g=null},j2=function(a,b,c,d,e,f,k,l){switch(f.tagName){case "b":k.bold=!0;
break;case "i":k.te=!0;break;case "u":k.underline=!0;break;case "font":var m=f.getAttribute("color");i2.test(m);k.color=m}for(m=0;m<f.childNodes.length;m++){var n=f.childNodes[m];if(3==n.nodeType)l.push(new F1(a,b,c,d,n.nodeValue,e||0<m,g.Qb(k)?void 0:k));else{var p={};g.Fa(p,k);j2(a,b,c,d,e||0<m,n,p,l)}}},k2=function(a,b){g2.call(this);
this.L=b;this.A={};this.H={};this.J={};this.B="_"+H1++;this.C=a;this.G={};this.l=this.g=null;this.F=!0},l2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return(0,window.parseFloat)(c)},m2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"==c},n2=function(a,b){var c=l2(a,b);
if(void 0!=c)return c},o2=function(a,b){var c=a.getAttribute(b);
if(null!=c)return i2.test(c),c},p2=function(a,b){var c={},d=b.getAttribute("ws");
g.Fa(c,d?a.J[d]:a.C);d=n2(b,"mh");null!=d&&(c.Up=d);d=n2(b,"ju");null!=d&&(c.textAlign=d);d=n2(b,"pd");null!=d&&(c.vg=d);d=n2(b,"sd");null!=d&&(c.es=d);d=o2(b,"wfc");null!=d&&(c.windowColor=d);d=l2(b,"wfo");void 0!=d&&(c.windowOpacity=d/255);return c},q2=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Fa(c,a.H[d]);d=n2(b,"ap");null!=d&&(c.Rf=d);d=l2(b,"cc");null!=d&&(c.zl=d);d=l2(b,"ah");null!=d&&(c.Te=d);d=l2(b,"rc");null!=d&&(c.qh=d);d=l2(b,"av");null!=d&&(c.yg=d);return c},r2=function(a,b,c,d){var e={};
g.Fa(e,q2(a,b));g.Fa(e,p2(a,b));d?g.Ub(e,a.C)?(d=a.B,e=a.C):d="_"+H1++:d=b.getAttribute("id")||"_"+H1++;a=l2(b,"t")+c;b=l2(b,"d")||0x8000000000000;return new G1(a,b,0,d,e)},s2=function(a,b,c,d,e,f,k){L1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.T=this.R=this.oa=this.ca=0;this.H=this.L=this.O=window.NaN;this.Ba=null;this.Y=new g.L(this.KG,433,this);g.I(this,this.Y)},t2=function(a){if(!a.ca){var b=g.xd("SPAN");
g.hh(b,M1(a,a.l.ib));a.o.appendChild(b);b.appendChild(g.yd("M"));var c=b.offsetHeight,d=g.xd("BR");b.appendChild(d);b.appendChild(g.yd("M"));a.ca=b.offsetHeight-c;a.o.removeChild(b)}return a.ca},u2=function(a){if(!a.oa){var b=g.xd("SPAN");
g.hh(b,M1(a,a.l.ib));K1(a,b);a.o.appendChild(b);b.appendChild(g.yd("\u9b31"));var c=b.offsetWidth,d=g.xd("BR");b.appendChild(d);b.appendChild(g.yd("\u9b31"));a.oa=b.offsetWidth-c;a.o.removeChild(b)}return a.oa},gpa=function(a){if((0,window.isNaN)(a.O)){var b=a.l.zl;
if(b){var c=g.xd("SPAN");g.Id(c,"\u2013".repeat(b));g.hh(c,M1(a,a.l.ib));a.o.appendChild(c);a.O=c.offsetWidth;a.o.removeChild(c)}else a.O=0}return a.O},hpa=function(a){if((0,window.isNaN)(a.L)){var b=a.l.zl;
if(b){var c=g.xd("SPAN");g.Id(c,"\u53e3".repeat(b));g.hh(c,M1(a,a.l.ib));a.o.appendChild(c);a.L=c.offsetHeight;a.o.removeChild(c)}else a.L=0}return a.L},v2=function(a,b,c,d,e,f,k){L1.call(this,a,b,c,d,e,f,k);
this.type=1},w2=function(a,b,c){this.F=c;
this.version=this.C=this.A=this.g=0;this.l=new window.DataView(a);this.o=[]},x2=function(a){var b=a.g;
a.g+=1;return a.l.getUint8(b)},y2=function(a){var b=a.g;
a.g+=4;return a.l.getUint32(b)},z2=function(a,b){g2.call(this);
this.l=a;this.track="CC3"==b.o?4:0;this.g=new Q1;this.g.o=1<<this.track},B2=function(a){if(g.t(a))return!1;
a=new w2(a,8,0);return A2(a)},A2=function(a){if(!(a.g<a.l.byteLength)||1380139777!=y2(a))return!1;
a.version=x2(a);if(1<a.version)return!1;x2(a);x2(a);x2(a);return!0},C2=function(a,b,c,d,e,f,k){L1.call(this,a,b,c,d,e,f,k);
g.J(this.element,"ytp-caption-window-rollup");this.type=2;this.H=[];this.O=this.L=this.Y=0;this.T=window.NaN;this.oa=0;this.ca=null;this.R=new g.L(this.LG,433,this);g.I(this,this.R)},ipa=function(a,b){return(a.C?b.offsetHeight:b.offsetWidth)+1},jpa=function(a){if((0,window.isNaN)(a.T)){var b=a.l.zl;
if(b){var c=g.xd("SPAN");g.Id(c,"\u2013".repeat(b));g.hh(c,M1(a,a.l.ib));a.o.appendChild(c);a.T=c.offsetWidth;a.o.removeChild(c)}else a.T=0}return a.T},kpa=function(a,b){if(!b)return"";
a.C&&1!=a.A.params.es&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},D2=function(a){a.H=Array.prototype.slice.call(g.kd("ytp-rollup-caption-line"));
for(var b=a.A.params.qh,c=0,d=0,e=a.H.length-1;c<b&&-1<e;){var f=a.H[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.H.length<b&&(d*=b/a.H.length);a.L=d;a.O=Math.max(jpa(a),a.oa,ipa(a,a.o))},lpa=function(a,b){D2(a);
var c=a.H.reduce(function(b,c){return(a.C?c.offsetWidth:c.offsetHeight)+b},0);
c=a.L-c;if(c!=a.Y){var d=0<c&&0==a.Y;b||(0,window.isNaN)(c)||d||(g.J(a.element,"ytp-rollup-mode"),g.In(a.R));g.hh(a.o,"transform",kpa(a,c));a.Y=c}D2(a)},E2=function(){g2.call(this)},F2=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.te=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var p=k.childNodes[n];if(3==p.nodeType){p=new F1(b,c,d,e.id,p.nodeValue,f||0<n,g.Qb(l)?void 0:l);m.push(p);var u=e;g.I(u,p);u.l.push(p)}else u={},g.Fa(u,l),F2(a,b,c,d,e,!0,p,u,m)}},G2=function(a){var b=0;
a=g.q(a.split(":"));for(var c=a.next();!c.done;c=a.next())b=60*b+(0,window.parseFloat)(c.value);return 1E3*b},H2=function(a,b,c,d){d=Object.assign({Up:0},d);
return new G1(a,b,c,"_"+H1++,d)},I2=function(a){g.G.call(this);
this.l=a;this.g=null},J2=function(a){var b={};
if(a=r1(a))b.lang=a,mpa.test(a)&&(b.vg=1);return b},M2=function(a){g.OI.call(this,a);
this.l=g.V(a);this.B=a.getVideoData();this.ua=g.fI(a);this.L=a;var b=null,c=g.wo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.go(c));this.X=b;this.A={ib:{}};this.C={ib:{}};this.J=[];this.T={};this.Y={};this.O=!1;this.ha=g.QP(this.B,this.L);this.Ha=!!this.B.captionTracks.length;this.Ba=this.B.Ek||this.l.Ek||this.ha;this.pa="3"==this.l.A;b=a.app.B;c=!(!b||!b.Fk());this.ra=!(!b||!b.uh());this.F=this.pa&&c&&!this.ha;this.Z=!this.F&&this.pa&&this.ra&&this.ha;this.o=this.G=this.H=this.R=
this.na=null;this.ea=new I2(this.l);g.I(this,this.ea);c=b=this.g=null;this.F||(b=new g.Fn(this.FA,void 0,this),g.I(this,b),c=new g.L(this.QM,2E3,this),g.I(this,c));this.ba=b;this.ca=c;this.da=new g.Qq(this);g.I(this,this.da);this.F||this.da.M(a,"resize",this.qs);this.da.M(a,"onPlaybackAudioChange",this.NI);this.da.M(a,g.fC("captions"),this.ME,this);this.da.M(a,"crx_captions",this.NE,this);K2(this,L2(this,"display-settings")||{})},N2=function(a){if(1==a.l.Vf||1==a.B.Vf||"alwayson"==g.AA(a.B,"yt:cc"))return!0;
if(2==a.l.Vf){var b=L2(a,"module-enabled");if(null!=b)return!!b}if(a.B.captionTracks.length)var c=a.player.getAudioTrack().xo;return"ON"==c||"on"==g.AA(a.B,"yt:cc")},O2=function(a,b){if(a.g&&(void 0===b||!b)||!a.B.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.Ll||"FORCED_ON"==c.xo},Q2=function(a,b){if(a.o){var c=t1(a.o.l,b||a.Ba);
if(a.G&&a.G.g)return a.G.g;for(var d=[a.B.Uf,a.l.Uf,g.AA(a.B,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(r1(c[f])==d[e])return c[f];return a.G&&a.G.Jo?a.G.Jo:(d=c.find(function(a){return a.isDefault}))?d:c[0]||P2(a)}return null},P2=function(a){return a.G&&a.G.Ll},R2=function(a){var b=P2(a);
return!!b&&a.g==b},S2=function(a,b){for(var c=a.L.app.B.ia().textTracks,d=a.g.toString(),e=0;e<c.length;e++){var f=c[e];
f.id==d&&(b?"showing"!=f.mode&&(f.mode="showing"):"showing"==f.mode&&(f.mode="disabled"))}},U2=function(a,b,c,d){a.loaded&&a.unload();
null!=c&&(a.O=c,a.O&&T2(a,"module-enabled",!!b));a.g=b;O2(a)&&(a.g=P2(a));a.load(d)},npa=function(a,b){var c=g.qK(a.ua,!0).height;
if(!c)return null;var d=a.ua.Ia();switch(null!=b.params.Up?b.params.Up:1<b.l.length?1:0){case 1:return new v2(b,a.A,a.C,c,d.width,d.height,a.l.experiments);case 2:return g.Q(a.l.experiments,"web_player_new_rollup_captions")?new C2(b,a.A,a.C,c,d.width,d.height,a.l.experiments):new s2(b,a.A,a.C,c,d.width,d.height,a.l.experiments);default:return new L1(b,a.A,a.C,c,d.width,d.height,a.l.experiments)}},K2=function(a,b,c){var d=V2.ib;
a.A={};g.Fa(a.A,V2);a.A.ib={};g.Fa(a.A.ib,d);a.C={ib:{}};var e=b.backgroundOverride?a.C:a.A,f=b.background||d.background;i2.test(f);e.ib.background=f;e=b.colorOverride?a.C:a.A;f=b.color||d.color;i2.test(f);e.ib.color=f;e=b.windowColorOverride?a.C:a.A;f=b.windowColor||V2.windowColor;i2.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.C:a.A;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.ib.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.C:a.A;f=b.fontSizeIncrement;null==f&&(f=d.fontSizeIncrement);
e.ib.fontSizeIncrement=f;f=b.fontStyleOverride?a.C:a.A;e=b.fontStyle;null==e&&(e=d.bold&&d.te?3:d.bold?1:d.te?2:0);f=f.ib;switch(e){case 1:f.bold=!0;delete f.te;break;case 2:delete f.bold;f.te=!0;break;case 3:f.bold=!0;f.te=!0;break;default:delete f.bold,delete f.te}e=b.textOpacityOverride?a.C:a.A;f=b.textOpacity;null==f&&(f=d.textOpacity);e.ib.textOpacity=f;e=b.windowOpacityOverride?a.C:a.A;f=b.windowOpacity;null==f&&(f=V2.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?a.C:a.A;f=b.charEdgeStyle;
null==f&&(f=d.charEdgeStyle);e.ib.charEdgeStyle=f;e=b.fontFamilyOverride?a.C:a.A;f=b.fontFamily;null==f&&(f=d.fontFamily);e.ib.fontFamily=f;a.loaded&&a.qs();c&&T2(a,"display-settings",b)},X2=function(a,b){if(b&&!a.H){var c=I1({vg:0,
lang:"tr"});a.H=[c,new F1(c.start,c.end-c.start,0,c.id,"Altyaz\u0131lar \u015fu \u015fekilde g\u00f6r\u00fcn\u00fcr")];g.rI(a.player,a.H)}else!b&&a.H&&(W2(a,a.H),a.H=null)},W2=function(a,b){g.uI(a.player,b);
(0,g.C)(b,function(a){g.Qa(this.J,a)},a);
a.ba.qj()},opa=function(a,b){return a&&g.t(a)&&i2.test(a)?a:b},ppa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?Math.max(0,Math.min(1,(0,window.parseFloat)(a))):b},qpa=function(a,b){return g.ua(a)&&!(0,window.isNaN)(a)?g.Wc(a,-2,4):b},L2=function(a,b){if(!a.X)return null;
try{var c=a.X.get(b)}catch(d){a.X.remove(b)}return c},T2=function(a,b,c){if(a.X)try{a.X.set(b,c)}catch(d){}};
g.oC.prototype.Wi=g.ca(13,function(){for(var a=g.jd(window.document,"track",void 0,this.g),b=0;b<a.length;b++)g.Cd(a[b])});
g.QF.prototype.Wi=g.ca(12,function(){this.l.Wi()});
g.oC.prototype.Fk=g.ca(11,function(){return!!this.g.textTracks});
g.QF.prototype.Fk=g.ca(10,function(){return this.l.Fk()});
g.oC.prototype.Ni=g.ca(9,function(a){for(var b=0;b<a.length;b++)this.g.appendChild(a[b])});
g.QF.prototype.Ni=g.ca(8,function(a){this.l.Ni(a)});
g.dB.prototype.uh=g.ca(7,function(){});
g.oC.prototype.uh=g.ca(6,function(){return!(!this.g.textTracks||!this.g.textTracks.addEventListener)});
g.QF.prototype.uh=g.ca(5,function(){return this.l.uh()});
g.Iu.prototype.Sl=g.ca(3,function(a){return(a=this.cg(a))?a.l:0});
g.Tw.prototype.Sl=g.ca(2,function(){return 0});
g.ft.prototype.eq=g.ca(1,function(a){return a?this.toString()==a.toString():!1});
var mpa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i,Voa=/#(.)(.)(.)/,Uoa=/^#(?:[0-9a-f]{3}){1,2}$/i,i2=/^#(?:[0-9a-f]{3}){1,2}$/i;g.r(v1,g.G);v1.prototype.gz=function(){return!1};
v1.prototype.U=function(){this.zg();g.G.prototype.U.call(this)};
g.r(w1,v1);w1.prototype.Rp=function(a,b){var c=this.oj(a),d=(0,g.z)(function(c){this.g=null;b(c.responseText,a)},this);
this.zg();this.g=g.Fp(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
w1.prototype.Sp=function(a,b,c,d){this.o=c;if(d)for(b=g.q(d.captionTracks),c=b.next();!c.done;c=b.next())u1(this.l,c.value);a()};
w1.prototype.oj=function(a,b){b=void 0===b?"srv3":b;var c=a.Jb(),d={fmt:this.o||b};a.g&&(d.tlang=a.g.languageCode);return g.wp(c,d)};
w1.prototype.zg=function(){this.g&&this.g.abort()};
x1.prototype.contains=function(a){a=g.Za(this.Xa,a);return 0<=a||0>a&&1==(-a-1)%2};
x1.prototype.length=function(){return this.Xa.length/2};
g.r(y1,g.G);g.h=y1.prototype;g.h.U=function(){g.G.prototype.U.call(this);this.l&&this.l.cancel()};
g.h.bx=function(a){var b=this;if(this.G.Sh())var c=this.B.M(this.A,"progresssync",function(){b.G.index.Ob()&&(b.reset(),b.g=null,z1(b,b.A.ya()),b.B.Pa(c))});
else z1(this,a)};
g.h.MG=function(){z1(this,this.A.ya())};
g.h.reset=function(){this.C=new x1;this.l&&(this.l.cancel(),this.l=null)};
g.h.Tv=function(){var a;if(a=null!==this.g)a=this.g,a=a.g.Cf(a);!a||this.l||this.g&&30<this.g.startTime-this.A.ya()||(a=this.g,a=a.g.Yh(a),a.g[0].duration&&(this.C.contains(a.g[0].l)||A1(this,a),this.g=g.Ha(a.g)));this.J.start()};
g.h.pL=function(a){var b=!(this.F?a.response:a.responseText)||400<=a.status,c=g.Yw(a);c?(a=g.Bw(this.o,this.L,{}),b=this.o,g.ww(b.l,a,c),b.requestId=a.get("req_id"),A1(this,this.o)):(b||null===this.H||(this.F?this.H(a.response,1E3*(this.o.g[0].startTime+g.AI(this.A))):this.H(a.responseText,1E3*(this.o.g[0].startTime+g.AI(this.A)))),this.l=this.o=null)};
g.r(B1,v1);g.h=B1.prototype;g.h.Rp=function(a,b){this.zg();var c=Xoa(this,a.getId());if(!c){var d=a.l;this.g.l?(c=D1(this,d,"386"),!c&&this.G&&(c=D1(this,d,"387"))):c=D1(this,d)}if(c){var e=1E3*(c.index.Sl(c.index.qe())-c.index.qd(c.index.qe()));this.o=new y1(new g.cw,this.A,c,function(c,d){b(c,a,d,e)},this.F||g.ut(c.info),(0,g.z)(function(){this.o&&this.o.reset();
this.B=!0},this))}};
g.h.gz=function(){var a=this.B;this.B=!1;return a};
g.h.Sp=function(a){if(this.F)var b=[new g.ft({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.ft({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})];else this.g.l?(b=C1(this,"386"),!b.length&&this.G&&(b=C1(this,"387"))):b=C1(this);b=g.q(b);for(var c=b.next();!c.done;c=b.next())u1(this.l,c.value);a()};
g.h.zg=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.oj=function(){return""};
g.r(E1,v1);E1.prototype.Rp=function(a,b){var c=this.oj(a),d=(0,g.z)(function(c){this.g=null;b(c.responseText,a)},this);
this.zg();this.g=g.Fp(c,{format:"RAW",onSuccess:d,withCredentials:!0})};
E1.prototype.Sp=function(a,b,c){this.o=c;c=this.B;var d={type:"list",tlangs:1,v:this.A,vssids:1};this.F&&(d.fmts=Number(b||!1));this.Bv&&(d.asrs=1);c=g.wp(c,d);b=(0,g.z)(function(b){this.g=null;if((b=b.responseXML)&&b.firstChild){for(var c=g.q(b.getElementsByTagName("track")),d=c.next();!d.done;d=c.next()){var e=d.value;d=e.getAttribute("lang_code");var m=e.getAttribute("lang_translated"),n=e.getAttribute("name"),p=e.getAttribute("kind"),u=e.getAttribute("id"),x="true"==e.getAttribute("lang_default"),
A="true"==e.getAttribute("cantran");e=e.getAttribute("vss_id");u1(this.l,new g.ft({languageCode:d,languageName:m,name:n,kind:p,id:u,is_servable:!0,is_translateable:A,vss_id:e,is_default:x}))}b=b.getElementsByTagName("target");c=b.length;for(d=0;d<c;d++)m=b[d].getAttribute("lang_code"),n=b[d].getAttribute("lang_translated"),p=b[d].getAttribute("lang_original"),u=b[d].getAttribute("id"),x="true"==b[d].getAttribute("lang_default"),m={languageCode:m,languageName:n,languageOriginal:p,id:u,is_default:x},
this.G[m.languageCode]=m.languageName,this.C.push(new g.et(m))}a()},this);
this.zg();this.g=g.Fp(c,{format:"RAW",onSuccess:b,withCredentials:!0})};
E1.prototype.oj=function(a,b){var c=this.B,d={v:this.A,type:"track",lang:a.l,name:a.B,kind:a.A,fmt:this.o||(void 0===b?"srv3":b)};a.g&&(d.tlang=r1(a));return c=g.wp(c,d)};
E1.prototype.zg=function(){this.g&&this.g.abort()};var Yoa=["left","right","center","justify"];var V2={windowColor:"#080808",windowOpacity:0,textAlign:2,Rf:7,Te:50,yg:100,ib:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(F1,g.cC);F1.prototype.toString=function(){return g.cC.prototype.toString.call(this)};g.r(G1,g.cC);G1.prototype.toString=function(){return g.cC.prototype.toString.call(this)};
var H1=0;g.r(L1,g.O);g.h=L1.prototype;g.h.JG=function(a,b){var c=g.yh(this.element,this.element.parentElement);this.pa=a-c.x;this.ra=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.IG=function(a,b){var c=g.Bh(this.element),d=a-this.pa-.02*this.Za,e=b-this.ra-.02*this.Wa,f=(d+c.width/2)/this.ha*3;f=Math.floor(g.Wc(f,0,2));var k=(e+c.height/2)/this.ua*3;k=Math.floor(g.Wc(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.ha;d=100*g.Wc(d,0,1);c=(e+k/2*c.height)/this.ua;c=100*g.Wc(c,0,1);this.A.params.Rf=l;this.A.params.yg=c;this.A.params.Te=d;this.l.Rf=l;this.l.yg=c;this.l.Te=d;this.Hr()};
g.h.HG=function(){g.yn(this.element,"ytp-dragging")};
g.h.Hr=function(){this.ge(this.B)};
g.h.ge=function(a){var b=Math.min(this.Uo(),this.ha),c=this.To(),d="";3==this.A.params.vg&&(d="rotate(180deg)");g.hh(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.mo(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.l.Te+2;d=this.l.Rf;switch(d){case 0:case 3:case 6:a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.o.offsetWidth;
b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.l.yg+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-b+"%"}g.hh(this.element,a)};
g.h.mo=function(a){var b;for(b=0;b<a.length&&a[b]==this.B[b];b++);if(this.X||this.B.length>b)b=0,this.X=!1,this.B=[],this.G=[],this.J=[],this.F=null,g.Ad(this.o);for(;b<a.length;b++)N1(this,a[b])};
g.h.Uo=function(){return 0};
g.h.To=function(){return 0};
g.h.Yi=function(a){a.appendChild(g.yd("\u00a0"));this.F=g.xd("SPAN");a.appendChild(this.F);g.J(this.F,"caption-visual-line");a.appendChild(g.yd("\u00a0"))};
g.h.toString=function(){return g.O.prototype.toString.call(this)};O1.prototype.B=function(){};Q1.prototype.clear=function(){this.A=this.l=this.mode=0;this.g=[];this.reset()};
Q1.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var R1=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];T1.prototype.set=function(a){this.g=a};
T1.prototype.get=function(){return this.g};
U1.prototype.clear=function(){this.g=0};
U1.prototype.update=function(){this.g=2==this.g?1:0};
U1.prototype.matches=function(a,b){return 0!=this.g&&a==this.o&&b==this.l};
V1.prototype.Bl=function(a){this.Rd=a.Rd;this.timestamp=a.timestamp};
V1.prototype.reset=function(){this.timestamp=this.Rd=0};
W1.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.o[b][c];a=0==d.Rd?a+"_":a+String.fromCharCode(d.Rd)}a+="\n"}return a};
W1.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.o[b][c].reset();this.A=a;this.g=0;this.l=this.row=1};
var bpa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],cpa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],dpa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],epa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];c2.prototype.reset=function(a,b){this.B=b;this.style.set(2);this.l=this.C;this.o=this.F;this.g=this.l;var c=(a<<2)+(b<<1);this.C.reset(c);this.F.reset(c);this.G.reset((a<<2)+(b<<1)+1)};
P1.prototype.reset=function(a){this.B=a;this.g.clear();this.A=this.o;this.o.reset(a,0);this.C.reset(a,1)};g.r(g2,g.G);g2.prototype.reset=function(){};g.r(h2,g2);
h2.prototype.o=function(a){var b=a.firstChild;a=[];this.g||(this.g=I1(this.l),a.push(this.g));b=Array.from(b.childNodes);b=g.q(b);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=this.g.id,e=c.getAttribute("t");e=e?(0,window.parseInt)(e,10):1E3*(0,window.parseFloat)(c.getAttribute("start")||0);var f=c.getAttribute("d");f=f?(0,window.parseFloat)(f):1E3*(0,window.parseFloat)(c.getAttribute("dur")||0);d=c.getAttribute("w")||d;var k=!!c.getAttribute("append"),l=k?6:5;c=g.Bn("<html>"+(c.firstChild&&
c.firstChild.nodeValue||"")+"</html>");j2(e,f,l,d,k,c.firstChild,{},a)}return a};g.r(k2,g2);k2.prototype.reset=function(){this.G={};this.l=this.g=null;this.F=!0};
k2.prototype.o=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.q(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.q(e),c=e.next();!c.done;c=e.next())if(c=c.value,1==c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.A,l={},m=c.getAttribute("p");m&&g.Fa(l,this.A[m]);m=m2(c,"b");null!=m&&(l.bold=
m);m=m2(c,"i");null!=m&&(l.te=m);m=m2(c,"u");null!=m&&(l.underline=m);m=n2(c,"et");null!=m&&(l.charEdgeStyle=m);m=n2(c,"of");null!=m&&(l.offset=m);m=o2(c,"bc");null!=m&&(l.background=m);m=o2(c,"ec");null!=m&&(l.Vt=m);m=o2(c,"fc");null!=m&&(l.color=m);m=n2(c,"fs");void 0!=m&&0!=m&&(l.fontFamily=m);m=l2(c,"sz");void 0!=m&&(l.fontSizeIncrement=m/100-1);m=l2(c,"bo");void 0!=m&&(l.backgroundOpacity=m/255);m=l2(c,"fo");void 0!=m&&(l.textOpacity=m/255);c=n2(c,"rb");void 0!=c&&(l.UM=c);k[d]=l;break;case "ws":d=
c.getAttribute("id");this.J[d]=p2(this,c);break;case "wp":d=c.getAttribute("id"),this.H[d]=q2(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.q(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1==d.nodeType)switch(d.tagName){case "w":this.g=r2(this,d,e,!1);g.I(this,this.g);(d=this.G[this.g.id])&&d.end>this.g.start&&(d.end=this.g.start);this.G[this.g.id]=this.g;c.push(this.g);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.B;m=!!m2(d,"a");n=(l2(d,"t")||0)+n;var p=l2(d,"d")||5E3;m||(!this.F&&
this.l&&this.l.windowId==l&&this.l.end>n&&(this.l.end=n),this.l&&"\n"==this.l.text&&(this.l.text=""));var u=m?6:5,x=this.A[d.getAttribute("p")],A=d.childNodes;A.length&&(this.F=null!=d.getAttribute("d"));for(var F=0;F<A.length;F++){var H=A[F];0<F&&(m=!0);var P=void 0;1==H.nodeType&&(P=H);if(P&&"s"==P.tagName)if((H=this.A[P.getAttribute("p")])&&1==H.UM&&g.Q(this.L.experiments,"web_player_ruby_text_captions")){H=n;var T=p,ab=l,Cb=m,ge=u;var Jc=P;var Tc=A[F+1],sg=A[F+2],Kc=A[F+3];Jc.getAttribute("p");
l2(Jc,"t");l2(Tc,"t");l2(sg,"t");l2(Kc,"t");P=g.xd("RUBY");Jc=Jc.textContent;var wl=g.xd("SPAN");wl.innerText=Jc;P.appendChild(wl);Tc.getAttribute("p");wl=g.xd("RP");Jc=Tc.textContent;wl.innerText=Jc;P.appendChild(wl);sg.getAttribute("p");Jc=sg.textContent;Tc=g.xd("RT");Tc.innerText=Jc;P.appendChild(Tc);Kc.getAttribute("p");Jc=Kc.textContent;Kc=g.xd("RP");Kc.innerText=Jc;P.appendChild(Kc);H=new F1(H,T,ge,ab,P,Cb,null);F+=3}else Kc=P,H=n,T=p,ab=l,Cb=m,ge=u,P=Kc.textContent?Kc.textContent:"",Jc=this.A[Kc.getAttribute("p")],
Kc=l2(Kc,"t")||0,H=new F1(H+Kc,T-Kc,ge,ab,P,Cb,Jc);else H=new F1(n,p,u,l,H.textContent||"",m,x);k.push(H);this.l=H}if(0<k.length)for(k[0].windowId==this.B&&(this.g=r2(this,d,e,!0),g.I(this,this.g),c.push(this.g)),d=g.q(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.g.id,l=this.g,g.I(l,k),l.l.push(k),c.push(k)}e=c}else e=[];return e};g.r(s2,L1);g.h=s2.prototype;g.h.Hr=function(){g.Jn(this.Y)};
g.h.KG=function(){g.yn(this.element,"ytp-rollup-mode");this.ge(this.Ba,!0)};
g.h.Uo=function(){return this.C?this.A.params.qh*u2(this):this.R};
g.h.To=function(){return this.C?this.T:this.A.params.qh*t2(this)};
g.h.Yi=function(a){L1.prototype.Yi.call(this,a);g.hh(this.F,"display","inline-block")};
g.h.ge=function(a,b){this.Ba=a;if(!this.C&&!t2(this)||this.C&&!u2(this))L1.prototype.ge.call(this,a);else{for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));c=this.R;d=this.T;this.T=this.R=0;L1.prototype.ge.call(this,a);this.C?(c=this.o.offsetHeight+1,this.T=Math.max(hpa(this),d,c),c=this.A.params.qh*u2(this)-this.o.offsetWidth,1!=this.A.params.es&&(c*=-1),c!=this.H&&(b||(0,window.isNaN)(this.H)||(g.J(this.element,"ytp-rollup-mode"),
g.In(this.Y)),g.hh(this.o,"transform",c?"translateX("+c+"px)":""),this.H=c)):(d=this.o.offsetWidth+1,this.R=Math.max(gpa(this),c,d),c=this.A.params.qh*t2(this)-this.o.offsetHeight,c!=this.H&&(b||(0,window.isNaN)(this.H)||(g.J(this.element,"ytp-rollup-mode"),g.In(this.Y)),g.hh(this.o,"transform",c?"translateY("+c+"px)":""),this.H=c));L1.prototype.ge.call(this,a)}};g.r(v2,L1);v2.prototype.mo=function(a){var b=this.A.l;L1.prototype.mo.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.l==e)var d=f;else{d={};g.Fa(d,c.l);g.Fa(d,rpa);var e=c.l;var f=d}N1(this,c,d)}};
var rpa={Yl:!0};g.r(w2,O1);w2.prototype.B=function(a,b,c,d,e){if(c<d){var f="_"+H1++;c=c/1E3-this.F;d=d/1E3-this.F;a=new G1(c,d-c,5,f,{textAlign:0,Rf:0,Te:2.5*b,yg:5.33*a});e=new F1(c,d-c,5,f,e);this.o.push(a);this.o.push(e)}};
g.r(z2,g2);z2.prototype.o=function(a){a=new w2(a,a.byteLength,this.l);if(A2(a)){for(;a.g<a.l.byteLength;)for(0==a.version?a.A=y2(a)*(1E3/45):1==a.version&&(a.A=4294967296*y2(a)+y2(a)),a.C=x2(a);0<a.C;a.C--){var b=x2(a),c=x2(a),d=x2(a);b&4&&(b&3)==this.track&&(0==this.track||1==this.track)&&(b=this.g,b.g.push({time:a.A,type:this.track,Pt:c,Qt:d,order:b.g.length}))}apa(this.g,a);return a.o}return[]};
z2.prototype.reset=function(){this.g.clear()};g.r(C2,L1);g.h=C2.prototype;g.h.Hr=function(){g.Jn(this.R)};
g.h.LG=function(){g.yn(this.element,"ytp-rollup-mode");this.ge(this.ca,!0)};
g.h.To=function(){return this.C?this.O:this.L};
g.h.Uo=function(){return this.C?this.L:this.O};
g.h.Yi=function(a){L1.prototype.Yi.call(this,a);g.hh(this.F,"display","inline-block");g.J(this.F,"ytp-rollup-caption-line")};
g.h.ge=function(a,b){this.ca=a;if(this.A.params.qh){for(var c=0,d=0;d<this.B.length&&c<a.length;d++)this.B[d]==a[c]&&c++;0<c&&c<a.length&&(a=this.B.concat(a.slice(c)));this.oa=this.O;this.L=this.O=0;L1.prototype.ge.call(this,a);lpa(this,b);L1.prototype.ge.call(this,a)}else L1.prototype.ge.call(this,a)};g.r(E2,g2);
E2.prototype.o=function(a,b){for(var c=[],d=a.split(spa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!=f&&!tpa.test(f)){var l=Y2.exec(f);if(l&&4<=l.length){var m=G2(l[1]),n=G2(l[2])-m;m+=k;var p,u=p=void 0,x=void 0,A=void 0,F=l[3];l={textAlign:2};F=g.q(F?F.split(" "):[]);for(var H=F.next();!H.done;H=F.next())if(H=H.value.split(":"),2==H.length){var P=H[1];switch(H[0]){case "line":H=P.split(",");H[0].endsWith("%")&&(A=H[0],l.yg=Number.parseInt(A,10),2==H.length&&(x=H[1].trim()));break;case "position":H=P.split(",");
u=H[0];l.Te=Number.parseInt(u,10);2==H.length&&(p=H[1].trim());break;case "align":switch(P){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}A||(l.yg=100,x||(x="end"));if(!u)switch(l.textAlign){case 0:l.Te=0;break;case 1:l.Te=100;break;default:l.Te=50}u=0;switch(x){case "center":u+=3;break;case "end":u+=6;break;default:u+=0}switch(p){case "line-left":u+=0;break;case "center":u+=1;break;case "line-right":u+=2;break;default:switch(l.textAlign){case 0:u+=
0;break;case 2:u+=1;break;case 1:u+=2}}l.Rf=0>u||8<u?7:u;p=l;f=f.substring(Y2.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=p;p=f;f={};if(0>p.indexOf("<")&&0>p.indexOf("&"))k=H2(m,n,5,u),n=new F1(m,n,5,k.id,p,!1,g.Qb(f)?void 0:f),c.push(k),c.push(n),g.I(k,n),k.l.push(n);else for(x=p.split(upa),1==x.length?(p=5,u=H2(m,n,p,u)):(A=p=6,u=Object.assign({zl:32},u),u=new G1(m,n,A,"_"+H1++,u)),c.push(u),A=m,l=0;l<x.length;l++)F=x[l],0==l%2?(H=g.Bn("<html>"+F+"</html>"),H.getElementsByTagName("parsererror").length?
(P=H.createElement("span"),P.appendChild(H.createTextNode(F))):P=H.firstChild,F2(this,A,n-(A-m),p,u,0<l,P,f,c)):A=G2(F)+k}Y2.lastIndex=0}}return c};
var tpa=/^NOTE/,spa=/(?:\r\n|\r|\n){2,}/,Y2=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),upa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(I2,g.G);I2.prototype.clear=function(){this.g&&this.g.dispose();this.g=null};
I2.prototype.reset=function(){this.g&&this.g.reset()};
I2.prototype.U=function(){this.clear();g.G.prototype.U.call(this)};g.r(M2,g.OI);g.h=M2.prototype;g.h.U=function(){if(this.F||this.Z){var a=this.L.app.B;a&&a.Wi()}else X2(this,!1);g.OI.prototype.U.call(this)};
g.h.rw=function(){return this.pa?this.F||this.Z:O2(this)?!0:N2(this)};
g.h.load=function(a){g.OI.prototype.load.call(this);this.G=this.player.getAudioTrack();if(this.o||a)this.g&&(this.ea.clear(),this.F?S2(this,!0):a?this.Ry(a,this.g):3!=this.player.Ea()&&this.o.Rp(this.g,(0,g.z)(this.Ry,this))),this.g&&!R2(this)?this.player.ma("captionschanged",q1(this.g)):this.player.ma("onCaptionsTrackListChanged");else{var b;this.ha?b=new B1(this.B.la,this.player):this.Ha?b=new w1(this.l,this.B):b=new E1(this.B.tl,this.B.videoId,this.B.Uf||this.l.Uf||g.AA(this.B,"yt:cc_default_lang")||
this.l.Mb,this.B.sl,this.l);this.o=b;g.I(this,this.o);b.Sp((0,g.z)(this.WL,this),!0,void 0,this.player.getAudioTrack())}};
g.h.unload=function(){this.F&&this.g?S2(this,!1):(this.ca&&g.Kn(this.ca),g.vI(this.player,"captions"),this.J=[],this.o&&this.o.zg(),this.ea.clear(),this.H&&g.rI(this.player,this.H),this.qs());g.OI.prototype.unload.call(this);var a=g.W(this.player.app);a&&a.A&&g.SA(a.A.o);this.player.ma("captionschanged",{})};
g.h.WL=function(){var a;this.O||N2(this)?a=Q2(this,this.O):O2(this)&&(a=P2(this));if(this.F||this.Z){for(var b=t1(this.o.l,!0),c=[],d=0;d<b.length;d++){var e=b[d],f={kind:"subtitles",label:g.gt(e),srclang:r1(e),id:e.toString()};this.Z||(f.src=this.o.oj(e,"vtt"));e==a&&(f["default"]=1);c.push(g.wd("TRACK",f))}this.L.app.B.Ni(c);a=this.L.app.B.ia();this.ra&&this.da.M(a.textTracks,"change",this.XL)}else!this.g&&a&&U2(this,a),this.player.ma("onCaptionsTrackListChanged"),this.player.ma("onApiChange")};
g.h.XL=function(){for(var a=this.L.app.B.ia().textTracks,b=null,c=0;c<a.length;c++)if("showing"==a[c].mode)a:{b=t1(this.o.l,!0);for(var d=0;d<b.length;d++)if(b[d].toString()==a[c].id){b=b[d];break a}b=null}(this.loaded?this.g:null)!=b&&U2(this,b,!0)};
g.h.tN=function(){!this.g&&this.F||this.unload()};
g.h.Ry=function(a,b,c,d){if(a){this.o.gz()&&(this.J=[],g.vI(this.L,"captions"),this.ba.qj(),this.ea.reset());var e=this.ea;c=c||0;d=d||0;if(!g.t(a)){var f=new window.DataView(a);if(8<=f.byteLength&&1718909296==f.getUint32(4)&&(f=g.$u(f,1835295092),a=a.slice(f.dataOffset,f.dataOffset+f.size),!B2(a)))if(g.Q(e.l.experiments,"web_player_utf8_binary_captions_killswitch")){a=new window.Uint8Array(a);f=[];for(var k=0,l=0;k<a.length;){var m=a[k++];if(128>m)f[l++]=String.fromCharCode(m);else if(191<m&&224>
m){var n=a[k++];f[l++]=String.fromCharCode((m&31)<<6|n&63)}else if(239<m&&365>m){n=a[k++];var p=a[k++],u=a[k++];m=((m&7)<<18|(n&63)<<12|(p&63)<<6|u&63)-65536;f[l++]=String.fromCharCode(55296+(m>>10));f[l++]=String.fromCharCode(56320+(m&1023))}else n=a[k++],p=a[k++],f[l++]=String.fromCharCode((m&15)<<12|(n&63)<<6|p&63)}a=f.join("")}else a=g.Sd(new window.Uint8Array(a))}if(a)try{if(g.t(a)){if("WEBVTT"==a.substring(0,6)){b=a;e.g||(e.g=new E2);var x=e.g.o(b,c);.01>Math.random()&&g.kp(Error("Deprecated subtitles format in web player: WebVTT"));
var A=x}else b:{x=a;var F=g.Bn(x);if(!F||!F.firstChild)throw Error("Invalid caption track data: "+x);if("timedtext"==F.firstChild.tagName){if(3==(0,window.parseInt)(F.firstChild.getAttribute("format"),10)){e.g||(e.g=new k2(J2(b),e.l));A=e.g.o(F,c);break b}throw Error("Unsupported subtitles format in web player: Format2");}if("transcript"==F.firstChild.tagName){e.g||(e.g=new h2(J2(b)));var H=e.g.o(F,c);.05>Math.random()&&g.kp(Error("Deprecated subtitles format in web player: Format1"));A=H}else throw Error("Invalid caption track data: "+
x);}var P=A}else{A=a;x=d;if(!B2(A))throw Error("Invalid binary caption track data");e.g||(e.g=new z2(x,b));P=e.g.o(A,c)}var T=P}catch(ab){g.M(ab),e.clear(),T=[]}else T=[];g.rI(this.player,T);!this.O||this.Z||R2(this)||g.ky(this.l)||g.ly(this.l)||(g.Kn(this.ca),T=I1({Rf:0,Te:5,yg:5,qh:2,textAlign:0,vg:0,lang:"tr"}),this.R=[T],e=["Ayarlar i\u00e7in "," simgesini t\u0131klay\u0131n"],this.na||(P=new g.Js(g.IN()),g.I(this,P),this.na=P.element),P=T.end-T.start,(b=g.gt(this.g))&&this.R.push(new F1(T.start,
P,0,T.id,b)),this.R.push(new F1(T.start,P,0,T.id,e[0]),new F1(T.start,P,0,T.id,this.na,!0),new F1(T.start,P,0,T.id,e[1],!0)),g.rI(this.player,this.R),g.In(this.ca));!this.O||this.Z||R2(this)||(T2(this,"module-enabled",!0),this.G&&(this.G.g=this.g),(T=g.W(this.player.app))&&T.A&&g.SA(T.A.o));this.O=!1}};
g.h.ME=function(a){this.J.push(a);this.ba.qj()};
g.h.NE=function(a){g.Qa(this.J,a);this.o instanceof B1&&this.o.F&&g.uI(this.player,[a]);this.ba.qj()};
g.h.JM=function(a){if(a instanceof G1){var b=this.T[a.id];b&&b.A!=a&&(b.dispose(),delete this.T[a.id],b=null);b||(b=npa(this,a))&&(this.T[a.id]=b)}else b=a.windowId,this.Y[b]||(this.Y[b]=[]),this.Y[b].push(a)};
g.h.QM=function(){W2(this,this.R);this.R=null};
g.h.FA=function(){this.ba.stop();g.Rb(this.Y);this.J.sort(g.eC);var a=this.J;if(this.H){var b=(0,g.Dd)(a,function(a){return-1==this.H.indexOf(a)},this);
b.length&&(a=b)}(0,g.C)(a,this.JM,this);g.Bb(this.T,function(a,b){this.Y[b]?(a.element.parentNode||g.zI(this.player,a.element,4),a.ge(this.Y[b])):(a.dispose(),delete this.T[b])},this)};
g.h.Dz=function(){K2(this,{},!0)};
g.h.bp=function(){var a=V2.ib;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.te?3:a.bold?1:a.te?2:0,textOpacity:a.textOpacity,windowColor:V2.windowColor,windowOpacity:V2.windowOpacity};var b=L2(this,"display-settings"),c;for(c in b)null!=b[c]&&(a[c]=b[c]);return a};
g.h.us=function(a,b){var c={};g.Fa(c,L2(this,"display-settings"));g.Fa(c,a);K2(this,c,b);this.player.P("captionssettingschanged")};
g.h.qs=function(){!this.F&&this.loaded&&(g.Bb(this.T,function(a,b){a.dispose();delete this.T[b]},this),this.FA())};
g.h.xm=function(a,b){switch(a){case "fontSize":if((0,window.isNaN)(b))break;var c=g.Wc(b,-2,4);this.us({fontSizeIncrement:c});return c;case "reload":b&&!this.F&&U2(this,this.g,!0);break;case "stickyLoading":void 0!=b&&this.l.vb&&T2(this,"module-enabled",!!b);break;case "track":if(!this.o)return{};if(b){if(this.F)break;if(!g.Ba(b))break;if(g.Qb(b)){U2(this,null,!0);break}var d;c=t1(this.o.l,!0);for(var e=0;e<c.length;e++){var f=c[e];f.l!=b.languageCode||d&&f.o!=b.languageName||(d=b.translationLanguage?
Toa(f,b.translationLanguage):f)}!d||d==this.g&&this.loaded||U2(this,d,!0)}else return this.loaded&&this.g&&!R2(this)?q1(this.g):{};return"";case "tracklist":return this.o?(0,g.E)(t1(this.o.l,!(!b||!b.includeAsr)),function(a){return q1(a)}):[];
case "translationLanguages":return this.o?this.o.C:[];case "displaySettings":d=this.bp();if(g.ky(this.l)&&b&&g.Ba(b))if(b.reset)this.Dz();else{f={};for(c in b)switch(c){case "color":case "background":case "windowColor":f[c]=opa(b[c],d[c]);break;case "textOpacity":case "backgroundOpacity":case "windowOpacity":f[c]=ppa(b[c],d[c]);break;case "charEdgeStyle":var k=g.pX[b[c]];f[c]=g.ua(k)?k:d[c];break;case "fontSizeIncrement":f[c]=qpa(b[c],d[c]);break;case "fontFamilyOption":k=g.oX[b[c]];f.fontFamily=
g.ua(k)?k:d[c];break;case "fontStyle":k=g.qX[b[c]],f[c]=g.ua(k)?k:d[c]}for(e in f)f[e+"Override"]=!0;this.us(f,!0);d=this.bp()}d.fontFamilyOption=g.mma[d.fontFamily];d.charEdgeStyle=g.nma[d.charEdgeStyle];d.fontStyle=g.oma[d.fontStyle];return d;case "sampleSubtitles":this.F||void 0==b||X2(this,!!b);break;case "xmlTrack":b&&this.l.vb&&(this.F||U2(this,new g.ft({languageName:b.name}),!1,b.xml))}};
g.h.KE=function(){var a="reload fontSize track tracklist translationLanguages displaySettings sampleSubtitle".split(" ");this.l.vb&&a.push("stickyLoading","xmlTrack");return a};
g.h.LE=function(){var a=this.g;return a?{cc:a.C}:{}};
g.h.uA=function(){this.loaded&&this.g&&!R2(this)?(T2(this,"module-enabled",!1),this.unload(),O2(this,!0)&&U2(this,P2(this),!1)):U2(this,R2(this)||!this.g?Q2(this,!0):this.g,!0)};
g.h.NI=function(){var a=R2(this);O2(this,a)?U2(this,this.player.getAudioTrack().Ll,!1):this.B.captionTracks.length&&(this.loaded&&this.unload(),this.rw()&&(a?U2(this,Q2(this),!1):this.load()))};g.bQ.captions=M2;})(_yt_player);
