(function(g){var window=this;var Z2=function(a,b,c){var d=b.za();g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.uc(c?c:"mqdefault.jpg");var f=b instanceof g.cA&&b.lengthSeconds?g.kO(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.gC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.cA?b.sa:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Oi||g.iM("\u0130zle: $TITLE",{TITLE:b.title}),duration:f,url:b.pj(),is_live:l,
is_list:k,is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.iC&&(d.playlist_length=b.getLength());a.update(d)},$2=function(a,b){g.Os.call(this,{D:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},a3=function(a){g.O.call(this,{D:"div",
I:"ytp-upnext",N:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",V:"S\u0131radaki"},{D:"span",I:"ytp-upnext-title",V:"{{title}}"},{D:"span",I:"ytp-upnext-author",V:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Sonraki videoyu oynat"},K:[{D:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",V:"Otomatik oynatma duraklat\u0131ld\u0131"}]}]});
this.B=null;var b=this.g["ytp-upnext-cancel"];this.B=new g.O({D:"button",W:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Otomatik oynatmay\u0131 iptal et"},V:"\u0130ptal"});g.I(this,this.B);this.B.ga("click",this.TI,this);this.B.aa(b);this.l=a;this.J=this.g["ytp-svg-autoplay-ring"];this.F=this.C=this.o=this.A=null;this.G=new g.L(this.xl,5E3,this);g.I(this,this.G);this.H=0;this.M(this.g["ytp-upnext-autoplay-icon"],"click",this.MK);this.iy();this.M(a,"autonavvisibility",this.iy);
this.M(a,"mdxnowautoplaying",this.bK);this.M(a,"mdxautoplaycanceled",this.cK);this.M(a,"mdxautoplayupnext",this.JA);3==this.l.Ea()&&(a=(a=g.gI(g.$H(this.l)))?a.HC():null)&&this.JA(a)},b3=function(a,b){if(!a.o){g.hr("a11y-announce","S\u0131radaki "+a.A.title);
a.H=g.rr();a.o=new g.L((0,g.z)(a.lo,a,b),25);a.lo(b);var c=b||g.R(g.V(a.l).experiments,"autoplay_time")||1E4;a.l.ma("onAutonavCoundownStarted",c)}g.yn(a.element,"ytp-upnext-autoplay-paused")},d3=function(a){c3(a);
a.H=g.rr();a.lo();g.J(a.element,"ytp-upnext-autoplay-paused")},c3=function(a){a.o&&(a.o.dispose(),a.o=null)},e3=function(a,b){b=void 0===b?!1:b;
if(g.Q(g.V(a.l).experiments,"autonav_notifications")&&b&&window.Notification&&window.document.hasFocus){var c=window.Notification.permission;"default"==c?window.Notification.requestPermission():"granted"!=c||window.document.hasFocus()||(c=a.A.za(),a.xl(),a.C=new window.Notification("S\u0131radaki",{body:c.title,icon:c.uc()}),a.F=a.M(a.C,"click",a.DK),a.G.start())}c3(a);a.l.gi(!1,b)},f3=function(a){$2.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.l=new g.O({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",N:{src:b.profilePicture}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",V:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.I(this,this.l);this.l.aa(this.element);this.o=new g.ET("Abone Ol",null,"Abonelikten \u00e7\u0131k",null,!0,!1,b.wh,b.subscribed,"trailer-endscreen",null,null,a);g.I(this,this.o);this.o.aa(this.l.g["html5-subscribe-button-container"]);this.hide()},
g3=function(a){var b=g.V(a),c=g.Dt||g.kh?{style:"will-change: opacity"}:void 0,d=b.l,e=["ytp-videowall-still"];
b.g&&e.push("ytp-videowall-show-text");g.O.call(this,{D:"a",W:e,N:{href:"{{url}}",target:d?"_blank":"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",N:c,K:[{D:"span",I:"ytp-videowall-still-info-title",V:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",V:"Canl\u0131"},{D:"span",I:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{D:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Oynatma Listesi",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",V:"{{playlist_length}}"},")"]}]},{D:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",
I:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.B=d;this.l=a;this.o=null;this.A=new g.Qq(this);g.I(this,this.A);this.ga("click",this.F);this.ga("keypress",this.G);this.A.M(a,"videodatachange",this.C);g.V(a).C&&g.sJ(a.app.L,this.element,this);this.C()},h3=function(a){g.EI(a.l,a.element);
var b=a.o.za().videoId,c=a.o.getPlaylistId();g.$V(a.l.app,b,a.o.cd,c,void 0,void 0,void 0)},i3=function(a){$2.call(this,a,"videowall-endscreen");
this.H=a;this.C=0;this.o=[];this.F=this.A=this.B=null;this.G=this.T=!1;this.O=null;this.da=new g.Qq(this);g.I(this,this.da);this.J=new g.L(g.Ea(g.J,this.element,"ytp-show-tiles"),0);g.I(this,this.J);var b=new g.O({D:"button",W:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"\u00d6nceki"},K:[g.pN()]});g.I(this,b);b.aa(this.element);b.ga("click",this.wG,this);this.L=new g.Js({D:"div",I:"ytp-endscreen-content"});g.I(this,this.L);this.L.aa(this.element);b=new g.O({D:"button",W:["ytp-button",
"ytp-endscreen-next"],N:{"aria-label":"Sonraki"},K:[g.qN()]});g.I(this,b);b.aa(this.element);b.ga("click",this.vG,this);this.l=new a3(a);g.I(this,this.l);g.zI(this.player,this.l.element,4);this.hide()},j3=function(a){return g.BI(a.player)&&a.Kt()&&!a.F},k3=function(a,b){return(0,g.E)(b.suggestions,function(b){b=g.iQ(g.V(a.H),b);
g.I(a,b);return b})},l3=function(a){var b=a.wq();
b!=a.T&&(a.T=b,a.player.P("autonavvisibility"))},n3=function(a){g.OI.call(this,a);
this.g=null;this.l=new g.Qq(this);g.I(this,this.l);this.o=g.V(a);m3(a)?this.g=new i3(this.player):this.o.Ha?this.g=new f3(this.player):this.g=new $2(this.player);g.I(this,this.g);g.zI(this.player,this.g.element,4);this.Cz();this.l.M(a,"videodatachange",this.Cz,this);this.l.M(a,g.fC("endscreen"),this.CE,this);this.l.M(a,"crx_endscreen",this.DE,this)},m3=function(a){a=g.V(a);
return a.Ba&&!a.Ha};
g.r($2,g.Os);$2.prototype.create=function(){this.created=!0};
$2.prototype.uq=function(){this.created=!1};
$2.prototype.Kt=function(){return!1};
$2.prototype.wq=function(){return!1};g.r(a3,g.O);g.h=a3.prototype;g.h.xl=function(){this.C&&(this.G.stop(),this.Pa(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.iy=function(){g.Ns(this,g.aI(this.l))};
g.h.DK=function(){window.focus();this.xl()};
g.h.hide=function(){g.O.prototype.hide.call(this)};
g.h.lo=function(a){a=a||g.R(g.V(this.l).experiments,"autoplay_time")||1E4;var b=Math.min(g.rr()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.l.Ea()?e3(this,!0):this.o&&this.o.start()};
g.h.MK=function(a){!g.Hd(this.B.element,g.Fq(a))&&g.SP(a,this.l)&&e3(this)};
g.h.TI=function(){g.cI(this.l,!0)};
g.h.bK=function(a){this.l.Ea();this.show();b3(this,a)};
g.h.JA=function(a){this.l.Ea();this.A&&this.A.za().videoId==a.za().videoId||(this.A=a,Z2(this,a,"hqdefault.jpg"))};
g.h.cK=function(){this.l.Ea();c3(this);this.hide()};
g.h.U=function(){c3(this);this.xl();g.O.prototype.U.call(this)};g.r(f3,$2);g.r(g3,g.O);g3.prototype.F=function(a){g.SP(a,this.l,this.B,this.o.cd||void 0)&&h3(this)};
g3.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.Kq(a)||(h3(this),g.Jq(a))}};
g3.prototype.C=function(){var a=this.l.getVideoData(),b=g.V(this.l);this.B=a.isDni?!1:b.l};g.r(i3,$2);g.h=i3.prototype;g.h.create=function(){$2.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.B=k3(this,a),this.A=a);this.Hf();this.da.M(this.player,"appresize",this.Hf);this.da.M(this.player,"onVideoAreaChange",this.Hf);this.da.M(this.player,"videodatachange",this.xG);this.da.M(this.player,"autonavchange",this.xq);this.da.M(this.player,"autonavcancel",this.uG);a=this.A.autonavState;a!=this.O&&this.xq(a);this.da.M(this.element,"transitionend",this.YL)};
g.h.uq=function(){g.Sq(this.da);g.Ze(this.o);this.o=[];this.B=null;$2.prototype.uq.call(this);g.yn(this.element,"ytp-show-tiles");this.J.stop();this.O=this.A.autonavState};
g.h.Kt=function(){return 1!=this.A.autonavState};
g.h.show=function(){$2.prototype.show.call(this);g.yn(this.element,"ytp-show-tiles");g.V(this.player).g?g.Jn(this.J):this.J.start();(this.G||this.F&&this.F!=this.A.clientPlaybackNonce)&&g.cI(this.player,!1);j3(this)?(l3(this),2==this.A.autonavState?g.Q(g.V(this.player).experiments,"fast_autonav_in_background")&&3==this.player.Ff()?e3(this.l,!0):b3(this.l):3==this.A.autonavState&&d3(this.l)):(g.cI(this.player,!0),l3(this))};
g.h.hide=function(){$2.prototype.hide.call(this);d3(this.l);l3(this)};
g.h.YL=function(a){g.Fq(a)==this.element&&this.Hf()};
g.h.Hf=function(){if(this.B&&this.B.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.oI(this.H,!0),b=g.ct(this.H);b&&(b=b.xc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.B.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var p=b/2,u=e/2,x=b<=f-2&&n>=u*m,A=e<=k-2&&n>=p*m;if((p+1)/u*d/c>c/(p/(u+1)*d)&&A)n-=p*m,e+=2;else if(x)n-=u*m,b+=2;else if(A)n-=p*m,e+=2;else break}d=
!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.Wc(a.width/m||1,1,1.21);n*=g.Wc(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.L.element;g.Ah(a,m,n);g.hh(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.l;f=this.B[0];c.A=f;Z2(c,f,"hqdefault.jpg");g.K(this.element,"ytp-endscreen-takeover",j3(this));l3(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(p=c,u=0,d&&f>=b-2&&k>=e-
2?u=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(u=2):u=2),p=g.Xc(p+this.C,l),0!=u){x=this.o[c];x||(x=new g3(this.player),this.o[c]=x,a.appendChild(x.element));A=Math.floor(n*k/e);var F=Math.floor(m*f/b),H=Math.floor(n*(k+u)/e)-A-4,P=Math.floor(m*(f+u)/b)-F-4;g.ph(x.element,F,A);g.Ah(x.element,P,H);g.hh(x.element,"transitionDelay",(k+f)/20+"s");g.K(x.element,"ytp-videowall-still-mini",1==u);g.K(x.element,"ytp-videowall-still-large",2<u);u=x;p=this.B[p];u.o!=p&&(u.o=p,Z2(u,p,g.wn(u.element,"ytp-videowall-still-large")?
"hqdefault.jpg":"mqdefault.jpg"),p=(p=p.cd)&&p.itct)&&(x=u.l,g.V(x).C&&g.tJ(x.app.L,u.element,p));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.o.length-1;b>=c;b--)e=this.o[b],g.Cd(e.element),g.Ye(e);this.o.length=c}};
g.h.xG=function(){var a=this.player.getVideoData();this.A!=a&&(this.C=0,this.B=k3(this,a),this.A=a,this.Hf())};
g.h.vG=function(){this.C+=this.o.length;this.Hf()};
g.h.wG=function(){this.C-=this.o.length;this.Hf()};
g.h.FD=function(){return!!this.l.o};
g.h.xq=function(a){1==a?(this.G=!1,this.F=this.A.clientPlaybackNonce,c3(this.l),this.La()&&this.Hf()):(this.G=!0,this.La()&&j3(this)&&(2==a?b3(this.l):3==a&&d3(this.l)))};
g.h.uG=function(a){if(a){for(a=0;a<this.o.length;a++)g.FI(this.H,this.o[a].element,!0);this.xq(1)}else this.F=null,this.G=!1;this.Hf()};
g.h.wq=function(){return this.La()&&j3(this)};g.r(n3,g.OI);g.h=n3.prototype;g.h.qw=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!m3(this.player)||b;a=g.FA(a,"ypc_module");var c=g.lV(this.player.app);return b&&!a&&!c};
g.h.pw=function(){return this.g.wq()};
g.h.CD=function(){return this.pw()?this.g.FD():!1};
g.h.U=function(){g.vI(this.player,"endscreen");g.OI.prototype.U.call(this)};
g.h.load=function(){g.OI.prototype.load.call(this);this.g.show()};
g.h.unload=function(){g.OI.prototype.unload.call(this);this.g.hide();this.g.uq()};
g.h.CE=function(a){this.qw()&&(this.g.created||this.g.create(),"load"==a.getId()&&this.load())};
g.h.DE=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.Cz=function(){g.vI(this.player,"endscreen");var a=Math.max(1E3*(this.player.getVideoData().lengthSeconds-10),0);a=new g.cC(a,0x8000000000000,{id:"preload",namespace:"endscreen"});g.I(this,a);var b=new g.cC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.I(this,b);g.rI(this.player,[a,b])};g.bQ.endscreen=n3;})(_yt_player);
