(function(g){var window=this;var r4=function(a){g.Os.call(this,{D:"div",I:"ytp-miniplayer-ui"});this.player=a;this.H=!1;this.G=this.B=this.l=void 0;this.M(a,"minimized",this.mK);this.M(a,"onStateChange",this.jN)},s4=function(a){g.OI.call(this,a);
this.g=new r4(this.player);this.g.hide();g.zI(this.player,this.g.element,4);a.app.H.g&&(this.load(),g.K(a.getRootNode(),"ytp-player-minimized",!0))};
g.r(r4,g.Os);g.h=r4.prototype;
g.h.show=function(){this.l=new g.Fn(this.FG,null,this);this.l.start();if(!this.H){this.F=new g.NT(this.player,this);g.I(this,this.F);g.zI(this.player,this.F.element,4);this.F.B=.6;this.O=new g.RS(this.player);g.I(this,this.O);this.C=new g.O({D:"div",I:"ytp-miniplayer-scrim"});g.I(this,this.C);this.C.aa(this.element);this.M(this.C.element,"click",this.My);var a=new g.O({D:"button",W:["ytp-miniplayer-close-button","ytp-button"],N:{"aria-label":"Kapat"},K:[g.uN()]});g.I(this,a);a.aa(this.C.element);
this.M(a.element,"click",this.ax);this.A=new g.O({D:"div",I:"ytp-miniplayer-controls"});g.I(this,this.A);this.A.aa(this.C.element);this.M(this.A.element,"click",this.My);var b=new g.O({D:"div",I:"ytp-miniplayer-button-container"});g.I(this,b);b.aa(this.A.element);a=new g.O({D:"div",I:"ytp-miniplayer-play-button-container"});g.I(this,a);a.aa(this.A.element);var c=new g.O({D:"div",I:"ytp-miniplayer-button-container"});g.I(this,c);c.aa(this.A.element);this.L=new g.mR(this.player,this,!1);g.I(this,this.L);
this.L.aa(b.element);b=new g.jR(this.player,this);g.I(this,b);b.aa(a.element);this.J=new g.mR(this.player,this,!0);g.I(this,this.J);this.J.aa(c.element);this.G=new g.vS(this.player,this);g.I(this,this.G);this.G.aa(this.C.element);this.B=new g.sR(this.player,this);g.I(this,this.B);g.zI(this.player,this.B.element,4);this.o=new g.O({D:"div",I:"ytp-miniplayer-buttons"});g.I(this,this.o);g.zI(this.player,this.o.element,4);this.o.hide();a=new g.O({D:"button",W:["ytp-miniplayer-close-button","ytp-button"],
N:{"aria-label":"Kapat"},K:[g.uN()]});g.I(this,a);a.aa(this.o.element);this.M(a.element,"click",this.ax);a=new g.O({D:"button",W:["ytp-miniplayer-replay-button","ytp-button"],N:{"aria-label":"Kapat"},K:[g.GN()]});g.I(this,a);a.aa(this.o.element);this.M(a.element,"click",this.nL);this.M(this.player,"presentingplayerstatechange",this.GG);this.M(this.player,"appresize",this.nb);this.M(this.player,"fullscreentoggled",this.nb);this.nb();this.H=!0}0!=this.player.Md()&&g.Os.prototype.show.call(this);this.B.show();
this.player.Uj("annotations_module")};
g.h.hide=function(){this.l&&(this.l.dispose(),this.l=void 0);g.Os.prototype.hide.call(this);this.player.app.H.g||(this.H&&this.B.hide(),this.player.fi("annotations_module"))};
g.h.U=function(){this.l&&(this.l.dispose(),this.l=void 0);g.Os.prototype.U.call(this)};
g.h.ax=function(){this.player.Lc();this.player.ma("onCloseMiniplayer")};
g.h.nL=function(){this.player.Qb()};
g.h.My=function(a){if(a.target==this.C.element||a.target==this.A.element)g.Q(g.V(this.player).experiments,"kevlar_miniplayer_scrim_pause")?2==this.player.Md()?this.player.Qb():this.player.Lb():this.player.ma("onExpandMiniplayer")};
g.h.mK=function(){g.K(this.player.getRootNode(),"ytp-player-minimized",this.player.app.H.g);this.player.app.H.g&&0==this.player.Md()?this.o.show():this.o.hide()};
g.h.FG=function(){g.uR(this.B);this.G.o();this.l&&this.l.start()};
g.h.GG=function(a){g.U(a.state,32)&&this.F.hide()};
g.h.nb=function(){var a=this.B,b=g.fI(this.player).Ia().width;a.Ka=0;a.B=b;a.F=!1;g.wR(a)};
g.h.jN=function(a){this.player.app.H.g&&(0==a?(this.hide(),this.o.show()):(this.show(),this.o.hide()))};
g.h.jb=function(){return this.F};
g.h.xc=function(){return!1};
g.h.Hv=function(){return!1};
g.h.Th=function(){return!1};
g.h.Vz=function(){};
g.h.Cl=function(){};
g.h.Dl=function(){};
g.h.Im=function(){return null};
g.h.zq=function(){return new g.Ug(0,0,0,0)};
g.h.Aq=function(){};
g.h.Bq=function(){};
g.h.cn=function(a,b,c,d,e){a.style.left="";a.style.top="";a.style.bottom="";d=g.Bh(a);var f=g.fI(this.player).Ia().width;b&&["ytp-prev-button","ytp-next-button"].some(function(a){return g.wn(b,a)})?(c=12,a.style.top=12+(e||0)+"px"):(c-=d.width/2,a.style.bottom=25+(e||0)+"px");
a.style.left=g.Wc(c,0,f-d.width)+"px"};
g.h.Jm=function(){};
g.h.Cq=function(){};g.r(s4,g.OI);s4.prototype.init=function(){};
s4.prototype.load=function(){this.player.Lw();this.g.show()};
s4.prototype.unload=function(){this.player.Ow();this.g.hide()};g.bQ.miniplayer=s4;})(_yt_player);
