(function(g){var window=this;var Cpa=function(a,b){return g.Nb(a,b)},t4=function(){},Dpa=function(a){if(a.wc&&"function"==typeof a.wc)return a.wc();
if(g.t(a))return a.split("");if(g.za(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Jb(a)},Epa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.za(a)||g.t(a))(0,g.C)(a,b,void 0);else{if(a.Id&&"function"==typeof a.Id)var c=a.Id();else if(a.wc&&"function"==typeof a.wc)c=void 0;else if(g.za(a)||g.t(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Kb(a);d=Dpa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},u4=function(a){g.Cm(a,"zx",g.rb());
return a},v4=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Hm(a.o,b,c)},w4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},x4=function(a){var b;
(b=a.g)||(b={},w4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},y4=function(a){return(a=w4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},z4=function(a,b){return b+" ["+a.X+" "+a.H+" "+a.getStatus()+"]"},Fpa=function(a){return"content-type"==a.toLowerCase()},A4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.v.clearTimeout(a.F),a.F=null)},Gpa=function(a){return g.rd&&g.ic(9)&&g.ua(a.timeout)&&g.sa(a.ontimeout)},B4=function(a){a.R||(a.R=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},C4=function(a,b){if(a.g){A4(a);
var c=a.g,d=a.O[0]?g.va:null;a.g=null;a.O=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},D4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;B4(a);C4(a)},E4=function(a){return a.g?a.g.readyState:0},F4=function(a){if(a.l&&"undefined"!=typeof g.pW)if(a.O[1]&&4==E4(a)&&2==a.getStatus())z4(a,"Local request error detected and ignored");
else if(a.G&&4==E4(a))g.lg(a.fv,0,a);else if(a.dispatchEvent("readystatechange"),4==E4(a)){z4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.xg(String(a.H))[1]||null;if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Hpa.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<E4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";B4(a)}}finally{C4(a)}}},G4=function(a){g.yf.call(this);
this.headers=new g.rm;this.T=a||null;this.l=!1;this.O=this.g=null;this.X=this.H="";this.A=0;this.B="";this.o=this.Y=this.G=this.R=!1;this.C=0;this.F=null;this.ea="";this.L=this.Z=!1},H4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Ipa=function(a,b){var c=[];
g.sk(b,function(a){try{var b=g.mo.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.sa(b)?g.lo(b)&&c.push(a):c.push(a)},a);
return c},Jpa=function(a,b){var c=Ipa(a,b);
(0,g.C)(c,function(a){g.mo.prototype.remove.call(this,a)},a)},I4=function(a){if(a.dd){if(a.dd.locationOverrideToken)return{locationOverrideToken:a.dd.locationOverrideToken};
if(null!=a.dd.latitudeE7&&null!=a.dd.longitudeE7)return{latitudeE7:a.dd.latitudeE7,longitudeE7:a.dd.longitudeE7}}return null},Kpa=function(a,b,c,d){var e=new g.um(null,void 0);
a&&g.vm(e,a);b&&g.wm(e,b);c&&g.xm(e,c);d&&(e.l=d);return e},J4=function(){this.g=[];
this.l=[]},K4=function(a){g.dr[a]&&(a=g.dr[a],(0,g.C)(a,function(a){g.br[a]&&delete g.br[a]}),a.length=0)},Lpa=function(a){var b=g.ar();
if(b)if(b.clear(a),a)K4(a);else for(var c in g.dr)K4(c)},L4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.rm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Mpa(this,a.capabilities||""),Npa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Mpa=function(a,b){a.capabilities.clear();
(0,g.Dd)(b.split(","),g.Ea(Cpa,Opa)).forEach(function(b){a.capabilities.add(b)})},Npa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},M4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},N4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},O4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Ppa=function(a){return new M4(a)},P4=function(a){return g.ya(a)?(0,g.E)(a,Ppa):[]},Q4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},R4=function(a){return g.ya(a)?"["+(0,g.E)(a,Q4).join(",")+"]":"null"},S4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Qpa=function(a){return(0,g.E)(a,function(a){return{key:a.id,
name:a.name}})},T4=function(a,b){return g.Ja(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},U4=function(a,b){return g.Ja(a,function(a){return N4(a,b)})},Rpa=function(){var a=(0,g.ns)();
a&&Jpa(a,a.g.gf(!0))},V4=function(){var a=g.qs("yt-remote-connected-devices")||[];
g.bb(a);return a},Spa=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.E)(a,function(a,b){return 0==b?a:a.substring(c.length)})},W4=function(a){g.ps("yt-remote-connected-devices",a,86400)},Y4=function(){if(X4)return X4;
var a=g.qs("yt-remote-device-id");a||(a=S4(),g.ps("yt-remote-device-id",a,31536E3));for(var b=V4(),c=1,d=a;g.Ma(b,d);)c++,d=a+"#"+c;return X4=d},Z4=function(){var a=V4(),b=Y4();
g.Ma(a,b);g.ts()&&g.db(a,b);a=Spa(a);if(0==a.length)try{g.Lr("remote_sid")}catch(c){}else try{g.Kr("remote_sid",a.join(","),-1)}catch(c){}},$4=function(){return g.qs("yt-remote-session-browser-channel")},a5=function(){return g.qs("yt-remote-local-screens")||[]},b5=function(){g.ps("yt-remote-lounge-token-expiration",!0,86400)},Tpa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.E)(a5(),function(a){return a.loungeToken}),c=(0,g.E)(a,function(a){return a.loungeToken});
(0,g.em)(c,function(a){return!g.Ma(b,a)})&&b5();
g.ps("yt-remote-local-screens",a,31536E3)},Upa=function(a,b){g.ps("yt-remote-session-browser-channel",a);
g.ps("yt-remote-session-screen-id",b);var c=V4(),d=Y4();g.Ma(c,d)||c.push(d);W4(c);Z4()},c5=function(a){a||(g.rs("yt-remote-session-screen-id"),g.rs("yt-remote-session-video-id"));
Z4();a=V4();g.Qa(a,Y4());W4(a)},e5=function(){if(!d5){var a=g.wo();
a&&(d5=new g.go(a))}return d5?!!d5.get("yt-remote-use-staging-server"):!1},Vpa=function(){var a=window.document.createElement("a");
g.Rc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.vb(a)},Wpa=function(a,b,c){c=void 0===c?null:c;
var d=g.xd("SCRIPT");d.id=a;d.onload=function(){b&&(0,window.setTimeout)(b,0)};
d.onreadystatechange=function(){switch(d.readyState){case "loaded":case "complete":d.onload()}};
c&&d.setAttribute("nonce",c);g.Uc(d,g.Qd("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));a=window.document.getElementsByTagName("head")[0]||window.document.body;a.insertBefore(d,a.firstChild);return d},Xpa=function(a){a=void 0===a?null:a;
var b=Vpa(),c=window.document.getElementById(b),d=c&&g.oq(c,"loaded");d||c&&!d||(c=Wpa(b,function(){g.oq(c,"loaded")||(g.nq(c,"loaded","true"),g.hr(b),g.op(g.Ea(Lpa,b),0))},a))},Ypa=function(){var a=void 0===a?null:a;
window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Xpa(a)},f5=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},g5=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},i5=function(a){a.length?h5(a.shift(),function(){i5(a)}):j5()},Zpa=function(a){return"chrome-extension://"+a+k5},h5=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},l5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},j5=function(){var a=g5();
a&&a(!1,"No cast extension found")},m5=function(){if($pa){var a=2,b=g5(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;h5("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",j5,c)}},aqa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(m5(),a({command:"cast.sender.init"}))},bqa=function(){m5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);i5(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+k5,"//www.gstatic.com/eureka/clank"+k5])},n5=function(a,b,c){g.G.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.Vc=b;this.B=(0,g.z)(this.LC,this);this.g=!1;this.l=0;this.o=this.Fa=null;this.A=[]},o5=function(){},p5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.da=new g.Im(this);this.l=new g.kg;this.l.setInterval(250)},r5=function(a,b,c){a.Lh=1;
a.gg=u4(b.clone());a.mh=c;a.B=!0;q5(a,null)},s5=function(a,b,c,d,e){a.Lh=1;
a.gg=u4(b.clone());a.mh=null;a.B=c;e&&(a.Jz=!1);q5(a,d)},q5=function(a,b){a.xi=(0,g.D)();
t5(a);a.ug=a.gg.clone();v4(a.ug,"t",a.C);a.Jk=0;a.oc=a.g.Io(a.g.Ak()?b:null);0<a.lp&&(a.gn=new g.Zk((0,g.z)(a.TA,a,a.oc),a.lp));a.da.ga(a.oc,"readystatechange",a.LM);var c=a.Rg?g.Vb(a.Rg):{};a.mh?(a.Ln="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.oc.send(a.ug,a.Ln,a.mh,c)):(a.Ln="GET",a.Jz&&!g.td&&(c.Connection="close"),a.oc.send(a.ug,a.Ln,null,c));a.g.Ae(1)},A5=function(a,b,c){for(var d=!0;!a.Ig&&a.Jk<c.length;){var e=cqa(a,c);
if(e==u5){4==b&&(a.hg=4,v5(15),d=!1);break}else if(e==w5){a.hg=4;v5(16);d=!1;break}else x5(a,e)}4==b&&0==c.length&&(a.hg=1,v5(17),d=!1);a.Ge=a.Ge&&d;d||(y5(a),z5(a))},cqa=function(a,b){var c=a.Jk,d=b.indexOf("\n",c);
if(-1==d)return u5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return w5;d+=1;if(d+c>b.length)return u5;var e=b.substr(d,c);a.Jk=d+c;return e},D5=function(a,b){a.xi=(0,g.D)();
t5(a);var c=b?window.location.hostname:"";a.ug=a.gg.clone();g.Cm(a.ug,"DOMAIN",c);g.Cm(a.ug,"t",a.C);try{a.He=new window.ActiveXObject("htmlfile")}catch(n){y5(a);a.hg=7;v5(22);z5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in B5)k=B5[l];else if(l in C5)k=B5[l]=C5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
B5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.Vc(g.qc("b/12014412"),d+"</body></html>");a.He.open();a.He.write(g.Nc(c));a.He.close();a.He.parentWindow.m=(0,g.z)(a.bM,a);a.He.parentWindow.d=(0,g.z)(a.Sy,a,!0);a.He.parentWindow.rpcClose=(0,g.z)(a.Sy,a,!1);c=a.He.createElement("DIV");a.He.parentWindow.document.body.appendChild(c);d=g.Bc(a.ug.toString());d=g.lb(g.yc(d));d=g.Vc(g.qc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Qc(c,g.Nc(d));a.g.Ae(1)},t5=function(a){a.As=(0,g.D)()+
a.A;
E5(a,a.A)},E5=function(a,b){if(null!=a.Ji)throw Error("WatchDog timer not null");
a.Ji=F5((0,g.z)(a.mM,a),b)},G5=function(a){a.Ji&&(g.v.clearTimeout(a.Ji),a.Ji=null)},z5=function(a){a.g.dv()||a.Ig||a.g.Wm(a)},y5=function(a){G5(a);
g.Ye(a.gn);a.gn=null;a.l.stop();g.Km(a.da);if(a.oc){var b=a.oc;a.oc=null;b.abort();b.dispose()}a.He&&(a.He=null)},x5=function(a,b){try{a.g.Ly(a,b),a.g.Ae(4)}catch(c){}},I5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;H5(a,b,function(e){e?c(!0):g.v.setTimeout(function(){I5(a,b,c,d,f)},f)})}},H5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{J5(d),c(!0)}catch(e){}};
d.onerror=function(){try{J5(d),c(!1)}catch(e){}};
d.onabort=function(){try{J5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{J5(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},J5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},K5=function(a){this.g=a;
this.l=new o5},M5=function(a){var b=L5(a.g,a.Qi,"/mail/images/cleardot.gif");
u4(b);I5(b.toString(),5E3,(0,g.z)(a.fC,a),3,2E3);a.Ae(1)},O5=function(a){var b=a.g.H;
if(null!=b)v5(5),b?(v5(11),N5(a.g,a,!1)):(v5(12),N5(a.g,a,!0));else if(a.Qd=new p5(a,void 0,void 0,void 0),a.Qd.Rg=a.jp,b=a.g,b=L5(b,b.Ak()?a.uj:null,a.kp),v5(5),!g.rd||g.jc(10))v4(b,"TYPE","xmlhttp"),s5(a.Qd,b,!1,a.uj,!1);else{v4(b,"TYPE","html");var c=a.Qd;a=!!a.uj;c.Lh=3;c.gg=u4(b.clone());D5(c,a)}},P5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new o5;this.G=a||null;this.H=null!=b?b:null;this.C=c||!1},dqa=function(a,b){this.g=a;
this.map=b;this.context=null},Q5=function(a){g.$e.call(this,"statevent",a)},R5=function(a,b){g.$e.call(this,"timingevent",a);
this.size=b},S5=function(a){g.$e.call(this,"serverreachability",a)},W5=function(a){T5(a);
if(3==a.g){var b=a.lk++,c=a.Ml.clone();g.Cm(c,"SID",a.o);g.Cm(c,"RID",b);g.Cm(c,"TYPE","terminate");U5(a,c);b=new p5(a,a.o,b,void 0);b.Lh=2;b.gg=u4(c.clone());(new window.Image).src=b.gg;b.xi=(0,g.D)();t5(b)}V5(a)},Y5=function(a){a.tC(1,0);
a.Ml=L5(a,null,a.ip);X5(a)},T5=function(a){a.Xf&&(a.Xf.abort(),a.Xf=null);
a.Sb&&(a.Sb.cancel(),a.Sb=null);a.jf&&(g.v.clearTimeout(a.jf),a.jf=null);Z5(a);a.yd&&(a.yd.cancel(),a.yd=null);a.dg&&(g.v.clearTimeout(a.dg),a.dg=null)},$5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new dqa(a.mI++,b));2!=a.g&&3!=a.g||X5(a)},X5=function(a){a.yd||a.dg||(a.dg=F5((0,g.z)(a.Qy,a),0),a.Hh=0)},c6=function(a,b){if(1==a.g){if(!b){a.lk=Math.floor(1E5*Math.random());
var c=a.lk++,d=new p5(a,"",c,void 0);d.Rg=null;var e=a6(a),f=a.Ml.clone();g.Cm(f,"RID",c);g.Cm(f,"CVER","1");U5(a,f);r5(d,f,e);a.yd=d;a.g=2}}else 3==a.g&&(b?b6(a,b):0==a.l.length||a.yd||b6(a))},b6=function(a,b){if(b)if(6<a.Jg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.lk-1;var d=a6(a)}else c=b.F,d=b.mh;else c=a.lk++,d=a6(a);var e=a.Ml.clone();g.Cm(e,"SID",a.o);g.Cm(e,"RID",c);g.Cm(e,"AID",a.Wh);U5(a,e);c=new p5(a,a.o,c,a.Hh+1);c.Rg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.yd=c;r5(c,e,d)},U5=function(a,b){if(a.Tc){var c=a.Tc.Mu();
c&&g.Bb(c,function(a,c){g.Cm(b,c,a)})}},a6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Jg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Jg?e:f-d;try{g.Bb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},d6=function(a){a.Sb||a.jf||(a.F=1,a.jf=F5((0,g.z)(a.Py,a),0),a.Ch=0)},f6=function(a){if(a.Sb||a.jf||3<=a.Ch)return!1;
a.F++;a.jf=F5((0,g.z)(a.Py,a),e6(a,a.Ch));a.Ch++;return!0},N5=function(a,b,c){a.Jn=c;
a.Ne=b.vf;a.C||Y5(a)},Z5=function(a){null!=a.Lg&&(g.v.clearTimeout(a.Lg),a.Lg=null)},e6=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},h6=function(a,b){if(2==b||9==b){var c=null;
a.Tc&&(c=null);var d=(0,g.z)(a.mN,a);c||(c=new g.um("//www.google.com/images/cleardot.gif"),u4(c));H5(c.toString(),1E4,d)}else v5(2);g6(a,b)},g6=function(a,b){a.g=0;
a.Tc&&a.Tc.St(b);V5(a);T5(a)},V5=function(a){a.g=0;
a.Ne=-1;if(a.Tc)if(0==a.A.length&&0==a.l.length)a.Tc.zo();else{g.Ta(a.A);var b=g.Ta(a.l);a.A.length=0;a.l.length=0;a.Tc.zo(b)}},L5=function(a,b,c){var d=g.Dm(c);
if(""!=d.g)b&&g.wm(d,b+"."+d.g),g.xm(d,d.B);else{var e=window.location;d=Kpa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.dj&&g.Bb(a.dj,function(a,b){g.Cm(d,b,a)});
g.Cm(d,"VER",a.Jg);U5(a,d);return d},F5=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},v5=function(a){i6.dispatchEvent(new Q5(i6,a))},j6=function(){},eqa=function(a,b){this.action=a;
this.params=b||{}},k6=function(a,b){g.G.call(this);
this.g=new g.L(this.UL,0,this);g.I(this,this.g);this.Vc=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},l6=function(a,b,c){this.L=a;
this.C=b;this.o=new g.fo;this.l=new k6(this.JN,this);this.g=null;this.J=!1;this.B=null;this.H="";this.G=this.A=0;this.F=[];this.O=c||!1},fqa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Jn,sessionId:a.g.o,arrayId:a.g.Wh}},m6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&c6(a.g),W5(a.g));a.G=0},n6=function(a){return!!a.g&&3==a.g.g},gqa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},o6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ag(a)||"";b&&(this.port=":"+b);this.domain=g.zg(a)||"";a=g.zb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.ub(a,"10.0")&&(this.l=!1))},p6=function(a,b){var c=a.g;
if(g.sa(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Jg(c+b,{})},q6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),sd:g.Ea(a.B,e)};c&&(a.tb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Fp(b,a)},hqa=function(){var a=r6;
s6();t6.push(a);u6(t6)},v6=function(a,b){s6();
var c=t6,d=iqa(a,String(b));0==c.length?jqa(d):(u6(c),(0,g.C)(c,function(a){a(d)}))},s6=function(){t6||(t6=g.y("yt.mdx.remote.debug.handlers_")||[],g.w("yt.mdx.remote.debug.handlers_",t6,void 0))},jqa=function(a){var b=(w6+1)%50;
w6=b;x6[b]=a;y6||(y6=49==b)},u6=function(a){var b=x6;
if(b[0]){var c=w6,d=y6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
x6=Array(50);w6=-1;y6=!1}},iqa=function(a,b){var c=((0,g.D)()-kqa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},z6=function(a){g.N.call(this);
this.F=a;this.g=[]},A6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},lqa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Dd)(a.g,function(a){return!!T4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=A6(a,b[d])||c;return c},mqa=function(a,b){var c=a.g.length;
a.g=(0,g.Dd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},B6=function(a,b,c,d){g.N.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Fa=window.NaN},D6=function(a){z6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;C6(this);this.info("Initializing with "+R4(this.g))},E6=function(a){if(a.g.length){var b=(0,g.E)(a.g,function(a){return a.id}),c=p6(a.o,"/pairing/get_lounge_token_batch");
q6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.UC,a),(0,g.z)(a.TC,a))}},C6=function(a){var b=P4(a5());
b=(0,g.Dd)(b,function(a){return!a.uuid});
return lqa(a,b)},F6=function(a,b){Tpa((0,g.E)(a.g,O4));
b&&b5()},H6=function(a,b){g.N.call(this);
this.C=b;var c=g.qs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Ma(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;G6("Initialized with "+g.qg(this.g))},I6=function(a,b,c){var d=p6(a.B,"/pairing/get_screen_availability");
q6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},J6=function(a,b){a:if(g.Hb(b)!=g.Hb(a.g))var c=!1;
else{c=g.Kb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(G6("Updated online screens: "+g.qg(a.g)),a.g=b,a.P("screenChange"));nqa(a)},K6=function(a){(0,window.isNaN)(a.o)||g.qp(a.o);
a.o=g.op((0,g.z)(a.Gr,a),0<a.A&&a.A<(0,g.D)()?2E4:1E4)},G6=function(a){v6("OnlineScreenService",a)},L6=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.Ib("Requesting availability of screen w/o lounge token.")});
return b},nqa=function(a){a=g.Kb(g.Db(a.g,function(a){return a}));
g.bb(a);a.length?g.ps("yt-remote-online-screen-ids",a.join(","),60):g.rs("yt-remote-online-screen-ids")},M6=function(a){z6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};oqa(this)},O6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.Kd();if(k=(c?U4(k,c):null)||U4(k,b)){k.uuid=b;var l=N6(a,k);I6(a.l,l,function(a){e(a?l:null)})}else c?pqa(a,c,(0,g.z)(function(a){var f=N6(this,new M4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));I6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},P6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},pqa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={tb:{screen_ids:b},method:"POST",context:a,onSuccess:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Fp(p6(a.C,"/pairing/get_lounge_token_batch"),e)},Q6=function(a){a.g=a.o.Kd();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+R4(a.g))},oqa=function(a){R6(a);
a.o=new D6(a.C);a.o.subscribe("screenChange",(0,g.z)(a.eD,a));Q6(a);a.A=P4(g.qs("yt-remote-automatic-screen-cache")||[]);R6(a);a.info("Initializing automatic screens: "+R4(a.A));a.l=new H6(a.C,(0,g.z)(a.Kd,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},N6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=U4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.ps("yt-remote-automatic-screen-cache",(0,g.E)(a.A,O4)));R6(a);a.B[b.uuid]=b.id;g.ps("yt-remote-device-id-map",a.B,31536E3);return b},R6=function(a){a.B=g.qs("yt-remote-device-id-map")||{}},S6=function(a,b,c){g.N.call(this);
this.O=c;this.H=a;this.l=b;this.o=null},T6=function(a,b){v6(a.O,b)},V6=function(a,b){S6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.PN,this);this.B=(0,g.z)(this.xM,this);this.A=g.op((0,g.z)(function(){U6(this,null)},this),12E4)},qqa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.qg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.va,(0,g.z)(function(){T6(this,"Failed to send message: getMdxSessionStatus.")},a)):T6(a,"Sending yt message without session: "+g.qg(b))},U6=function(a,b){g.qp(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Xm,a),d=(0,g.z)(a.Od,a);a.Vu(b,c,d,5)}}else a.Od(Error("Waiting for session status timed out."))},W6=function(a,b,c){S6.call(this,a,b,"DialSession");
this.A=this.G=null;this.J="";this.T=c;this.B=null;this.F=g.va;this.C=window.NaN;this.L=(0,g.z)(this.SN,this);this.g=g.va},X6=function(a){a.g=a.H.bB(a.J,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.va;
this.Xm(a)},a),(0,g.z)(function(a){this.g=g.va;
this.Od(a)},a))},Y6=function(a){var b={};
b.pairingCode=a.J;b.theme=a.T;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}e5()&&(b.env_useStageMdx=1);return g.Hg(b)},Z6=function(a,b){S6.call(this,a,b,"ManualSession");
this.g=g.op((0,g.z)(this.Xh,this,null),150)},$6=function(a,b,c,d){g.N.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.hL,this)},a7=function(a,b){return b?g.Ja(a.o,function(a){return N4(b,a.label)},a):null},b7=function(a){v6("Controller",a)},r6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},c7=function(a){return a.B||!!a.o.length||!!a.g},d7=function(a,b,c){b!=a.g&&(g.Ye(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.Oy,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Xh(null)):a.P("yt-remote-cast2-session-change",null))},e7=function(a){var b=a.l.aB(),c=a.g&&a.g.l;
a=(0,g.E)(b,function(a){c&&N4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=a7(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uqa=function(a,b,c,d,e,f,k){rqa()?sqa(b,e,f,k)&&(g7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?h7(a,c):(window.__onGCastApiAvailable=function(b,d){b?h7(a,c):(i7("Failed to load cast API: "+d),j7(!1),g7(!1),g.rs("yt-remote-cast-available"),g.rs("yt-remote-cast-receiver"),k7(),c(!1))},
d?Ypa():l5("CriOS")?aqa():l5("Android")&&l5("Chrome/")&&window.navigator.presentation?bqa():window.chrome&&window.navigator.presentation&&!l5("Edge")?(m5(),i5(tqa.map(Zpa))):j5())):f7("Cannot initialize because not running Chrome")},k7=function(){f7("dispose");
var a=l7();a&&a.dispose();g.w("yt.mdx.remote.cloudview.instance_",null,void 0);m7(!1);g.fr(n7);n7.length=0},o7=function(){return!!g.qs("yt-remote-cast-installed")},p7=function(){var a=g.qs("yt-remote-cast-receiver");
return a?a.friendlyName:null},q7=function(){f7("clearCurrentReceiver");
g.rs("yt-remote-cast-receiver")},r7=function(){return o7()?l7()?l7().getCastSession():(i7("getCastSelector: Cast is not initialized."),null):(i7("getCastSelector: Cast API is not installed!"),null)},t7=function(){o7()?l7()?s7()?(f7("Requesting cast selector."),l7().requestSession()):(f7("Wait for cast API to be ready to request the session."),n7.push(g.er("yt-remote-cast2-api-ready",t7))):i7("requestCastSelector: Cast is not initialized."):i7("requestCastSelector: Cast API is not installed!")},u7=
function(a,b){s7()?l7().setConnectedScreenStatus(a,b):i7("setConnectedScreenStatus called before ready.")},rqa=function(){var a=0<=g.zb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Dt||a},vqa=function(a,b){l7().init(a,b)},sqa=function(a,b,c,d){var e=!1;
l7()||(a=new $6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.ps("yt-remote-cast-available",a);g.ir("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){f7("onReceiverSelected: "+a.friendlyName);
g.ps("yt-remote-cast-receiver",a);g.ir("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){f7("onReceiverResumed: "+a.friendlyName);
g.ps("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){f7("onSessionChange: "+Q4(a));
a||g.rs("yt-remote-cast-receiver");g.ir("yt-remote-cast2-session-change",a)}),g.w("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
f7("cloudview.createSingleton_: "+e);return e},l7=function(){return g.y("yt.mdx.remote.cloudview.instance_")},h7=function(a,b){j7(!0);
g7(!1);vqa(a,function(a){a?(m7(!0),g.hr("yt-remote-cast2-api-ready")):(i7("Failed to initialize cast API."),j7(!1),g.rs("yt-remote-cast-available"),g.rs("yt-remote-cast-receiver"),k7());b(a)})},f7=function(a){v6("cloudview",a)},i7=function(a){v6("cloudview",a)},j7=function(a){f7("setCastInstalled_ "+a);
g.ps("yt-remote-cast-installed",a)},s7=function(){return!!g.y("yt.mdx.remote.cloudview.apiReady_")},m7=function(a){f7("setApiReady_ "+a);
g.w("yt.mdx.remote.cloudview.apiReady_",a,void 0)},g7=function(a){g.w("yt.mdx.remote.cloudview.initializing_",a,void 0)},v7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.C=this.F=0;this.g=null;this.hasNext=this.Pe=!1;this.H=this.G=this.l=this.A=0;this.o=window.NaN;this.B=!1;this.reset(a)},w7=function(a){a.audioTrackId=null;
a.g=null;a.playerState=-1;a.Pe=!1;a.hasNext=!1;a.F=0;a.C=(0,g.D)();a.A=0;a.l=0;a.G=0;a.H=0;a.o=window.NaN;a.B=!1},x7=function(a){return 1==a.playerState?((0,g.D)()-a.C)/1E3:0},y7=function(a,b){a.F=b;
a.C=(0,g.D)()},z7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.D)()-a.C)/1E3+a.F;
case -1E3:return 0}return a.F},A7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&w7(a)},B7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Wb(a.g);b.hasPrevious=a.Pe;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.C;b.seekableStart=a.A;b.seekableEnd=a.l;b.duration=a.G;b.loadedTime=a.H;b.liveIngestionTime=a.o;return b},E7=function(a,b){g.N.call(this);
this.g=0;this.A=a;this.C=[];this.B=new J4;this.o=this.l=null;this.H=(0,g.z)(this.WI,this);this.F=(0,g.z)(this.mk,this);this.G=(0,g.z)(this.VI,this);this.J=(0,g.z)(this.jJ,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ds,this),C7(this))):c=3;0!=c&&(b?this.Ds(c):g.op((0,g.z)(function(){this.Ds(c)},this),0));
var d=r7();d&&D7(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},F7=function(a){return new v7(a.A.getPlayerContextData())},C7=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.dL,a),this))},a)},G7=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},H7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},J7=function(a,b,c){var d=F7(a);
y7(d,c);-1E3!=d.playerState&&(d.playerState=b);I7(a,d)},K7=function(a,b,c){a.A.sendMessage(b,c)},I7=function(a,b){G7(a);
a.A.setPlayerContextData(B7(b));C7(a)},D7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.F),a.mk(null));
a.o=b;a.o&&(v6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.F),a.o.media.length&&a.mk(a.o.media[0]))},L7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=F7(a);b.contentId!=d.videoId&&v6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;y7(d,a.l.getEstimatedTime());I7(a,d)}else v6("CP","No cast media video. Ignoring state update.")},M7=function(a,b,c){return(0,g.z)(function(a){this.Ib("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Ib("Retrying "+b+" using MDx browser channel."),K7(this,b,c))},a)},N7=function(a,b,c){g.N.call(this);
this.B=window.NaN;this.T=!1;this.J=this.H=this.L=this.O=window.NaN;this.R=[];this.A=this.F=this.o=this.Sa=this.g=null;this.pa=a;this.R.push(g.Dq(window,"beforeunload",(0,g.z)(this.NC,this)));this.l=[];this.Sa=new v7;this.Y=b.id;this.g=wqa(this,c);this.g.subscribe("handlerOpened",this.aJ,this);this.g.subscribe("handlerClosed",this.XI,this);this.g.subscribe("handlerError",this.YI,this);this.g.subscribe("handlerMessage",this.ZI,this);gqa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Sa.videoId;g.ts()&&g.ps("yt-remote-session-video-id",a)},this)},O7=function(a){v6("conn",a)},wqa=function(a,b){return new l6(p6(a.pa,"/bc"),b)},P7=function(a,b){a.P("proxyStateChange",b)},xqa=function(a){a.B=g.op((0,g.z)(function(){O7("Connecting timeout");
this.C(1)},a),2E4)},Q7=function(a){g.qp(a.B);
a.B=window.NaN},R7=function(a){g.qp(a.O);
a.O=window.NaN},yqa=function(a){S7(a);
a.L=g.op((0,g.z)(function(){T7(this,"getNowPlaying")},a),2E4)},S7=function(a){g.qp(a.L);
a.L=window.NaN},V7=function(a,b){b&&(Q7(a),R7(a));
b==(n6(a.g)&&(0,window.isNaN)(a.B))?b&&(P7(a,1),T7(a,"getSubtitlesTrack")):b?(a.Z()&&a.Sa.reset(),P7(a,1),T7(a,"getNowPlaying"),U7(a)):a.C(1)},zqa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Sa.videoId&&(g.Qb(b.params)?a.Sa.g=null:a.Sa.g=b.params,a.P("remotePlayerChange"))},W7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Sa.listId=b.params.listId||a.Sa.listId;A7(a.Sa,c,d);a.P("remoteQueueChange")},Aqa=function(a,b){b.params=b.params||{};
W7(a,b);X7(a,b);a.P("autoplayDismissed")},X7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
y7(a.Sa,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Sa.playerState&&(c=-1E3);a.Sa.playerState=c;c=Number(b.params.loadedTime);a.Sa.H=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Sa.G=(0,window.isNaN)(c)?0:c;c=a.Sa;var d=Number(b.params.liveIngestionTime);c.o=d;c.B=(0,window.isNaN)(d)?!1:!0;c=a.Sa;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.A=(0,window.isNaN)(d)?0:d;c.l=(0,window.isNaN)(e)?0:
e;1==a.Sa.playerState?yqa(a):S7(a);a.P("remotePlayerChange")},Bqa=function(a,b){if(-1E3!=a.Sa.playerState){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Sa.playerState=c;c=(0,window.parseInt)(b.params.currentTime,10);y7(a.Sa,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},Cqa=function(a,b){var c="true"==b.params.muted;
a.Sa.volume=(0,window.parseInt)(b.params.volume,10);a.Sa.muted=c;a.P("remotePlayerChange")},Dqa=function(a,b){a.F=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Eqa=function(a,b){var c="true"==b.params.hasNext;
a.Sa.Pe="true"==b.params.hasPrevious;a.Sa.hasNext=c;a.P("previousNextChange")},U7=function(a){g.qp(a.J);
a.J=g.op((0,g.z)(a.C,a,1),864E5)},T7=function(a,b,c){c?O7("Sending: action="+b+", params="+g.qg(c)):O7("Sending: action="+b);
a.g.sendMessage(b,c)},Y7=function(a){z6.call(this,"ScreenServiceProxy");
this.Kc=a;this.l=[];this.l.push(this.Kc.$_s("screenChange",(0,g.z)(this.NN,this)));this.l.push(this.Kc.$_s("onlineScreenChange",(0,g.z)(this.GK,this)))},Jqa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ep("MDX_CONFIG")||b;Rpa();Z4();Z7||(Z7=new o6(b?b.loungeApiHost:void 0),e5()&&(Z7.g="/api/loungedev"));$7||($7=g.y("yt.mdx.remote.deferredProxies_")||[],g.w("yt.mdx.remote.deferredProxies_",$7,void 0));Fqa();var c=a8();if(!c){var d=new M6(Z7);g.w("yt.mdx.remote.screenService_",d,void 0);c=a8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);uqa(a,d,function(a){a?b8()&&u7(b8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.ir("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.y("yt.mdx.remote.initialized_")&&(g.w("yt.mdx.remote.initialized_",!0,void 0),c8("Initializing: "+g.qg(b)),d8.push(g.er("yt-remote-cast2-availability-change",function(){g.ir("yt-remote-receiver-availability-change")})),d8.push(g.er("yt-remote-cast2-receiver-selected",function(){e8(null);
g.ir("yt-remote-auto-connect","cast-selector-receiver")})),d8.push(g.er("yt-remote-cast2-receiver-resumed",function(){g.ir("yt-remote-receiver-resumed","cast-selector-receiver")})),d8.push(g.er("yt-remote-cast2-session-change",Gqa)),d8.push(g.er("yt-remote-connection-change",function(a){a?u7(b8(),"YouTube TV"):f8()||(u7(null,null),q7())})),a=g8(),b.isAuto&&(a.id+="#dial"),g.lp("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),c8(" -- with channel params: "+
g.qg(a)),Hqa(a),c.start(),b8()||Iqa())},Kqa=function(){var a=h8();
o7()&&g.qs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},h8=function(){var a=a8().Kc.$_gos();
var b=i8();b&&j8()&&(T4(a,b)||a.push(b));return Qpa(a)},k8=function(){var a=Lqa();
!a&&o7()&&p7()&&(a={key:"cast-selector-receiver",name:p7()});return a},Lqa=function(){var a=h8(),b=i8();
b||(b=f8());return g.Ja(a,function(a){return b&&N4(b,a.key)?!0:!1})},i8=function(){var a=b8();
if(!a)return null;var b=a8().Kd();return U4(b,a)},Gqa=function(a){c8("remote.onCastSessionChange_: "+Q4(a));
if(a){var b=i8();b&&b.id==a.id?u7(b.id,"YouTube TV"):(b&&l8(),m8(a,1))}else j8()&&l8()},l8=function(){s7()?l7().stopSession():i7("stopSession called before API ready.");
var a=j8();a&&(a.disconnect(1),n8(null))},o8=function(){var a=j8();
return!!a&&3!=a.getProxyState()},c8=function(a){v6("remote",a)},a8=function(){if(!p8){var a=g.y("yt.mdx.remote.screenService_");
p8=a?new Y7(a):null}return p8},b8=function(){return g.y("yt.mdx.remote.currentScreenId_")},q8=function(a){g.w("yt.mdx.remote.currentScreenId_",a,void 0)},r8=function(){return g.y("yt.mdx.remote.connectData_")},e8=function(a){g.w("yt.mdx.remote.connectData_",a,void 0)},j8=function(){return g.y("yt.mdx.remote.connection_")},n8=function(a){var b=j8();
e8(null);a||q8("");g.w("yt.mdx.remote.connection_",a,void 0);$7&&((0,g.C)($7,function(b){b(a)}),$7.length=0);
b&&!a?g.ir("yt-remote-connection-change",!1):!b&&a&&g.ir("yt-remote-connection-change",!0)},f8=function(){var a=g.ts();
if(!a)return null;var b=a8().Kd();return U4(b,a)},m8=function(a,b){i8()&&i8();
q8(a.id);var c=new N7(Z7,a,g8());c.connect(b,r8());c.subscribe("beforeDisconnect",function(a){g.ir("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){j8()&&n8(null)});
n8(c)},Iqa=function(){var a=f8();
a?(c8("Resume connection to: "+Q4(a)),m8(a,0)):(c5(),q7(),c8("Skipping connecting because no session screen found."))},Fqa=function(){var a=g8();
if(g.Qb(a)){a=Y4();var b=g.qs("yt-remote-session-name")||"",c=g.qs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.w("yt.mdx.remote.channelParams_",a,void 0)}},g8=function(){return g.y("yt.mdx.remote.channelParams_")||{}},Hqa=function(a){a?(g.ps("yt-remote-session-app",a.app),g.ps("yt-remote-session-name",a.name)):(g.rs("yt-remote-session-app"),g.rs("yt-remote-session-name"));
g.w("yt.mdx.remote.channelParams_",a,void 0)},s8=function(a,b,c){g.G.call(this);
this.B=a;this.l=b;this.o=new g.Qq(this);g.I(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.ZJ);this.o.M(b,"captionschanged",this.UI);this.o.M(b,"captionssettingschanged",this.kA);this.o.M(b,"videoplayerreset",this.Ym);this.o.M(b,"mdxautoplaycancel",this.eC);this.R=this.o.M(b,"onVolumeChange",this.zy);this.G=!1;this.g=c;c.subscribe("proxyStateChange",this.Ky,this);c.subscribe("remotePlayerChange",this.pk,this);c.subscribe("remoteQueueChange",this.Ym,this);c.subscribe("autoplayUpNext",this.ky,
this);c.subscribe("previousNextChange",this.Hy,this);c.subscribe("nowAutoplaying",this.Dy,this);c.subscribe("autoplayDismissed",this.jy,this);this.suggestion=null;this.H=new g.nB(64);this.A=new g.L(this.hA,500,this);g.I(this,this.A);this.C=new g.L(this.iA,1E3,this);g.I(this,this.C);this.L=new n5(this.uN,0,this);g.I(this,this.L);this.F={};this.O=new g.L(this.KA,1E3,this);g.I(this,this.O);this.J=new g.Zk(this.EG,1E3,this);g.I(this,this.J);this.T=g.va;this.kA();this.Ym();this.pk()},t8=function(a,b){var c=
a.B,d=a.l.getVideoData().lengthSeconds;
c.C=b||0;c.player.P("progresssync",b,d)},v8=function(a){t8(a,0);
a.A.stop();u8(a,new g.nB(64))},x8=function(a,b){if(w8(a)&&!a.G){var c=null;
b&&(c={style:a.l.Ef()},g.Yb(c,b));a.g.Xz(a.l.getVideoData(1).videoId,c);a.F=F7(a.g).g}},y8=function(a,b){var c=a.l.We();
if(c){var d=c.Ua;var e=c.listId.toString()}var f=a.l.getVideoData(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;var m=f.Ph;f=I4(f);var n=F7(c);l=l||0;var p={videoId:k,currentIndex:l};A7(n,k,l);g.sa(b)&&(y7(n,b),p.currentTime=b);g.sa(e)&&(p.listId=e);null!=d&&(p.playerParams=d);null!=m&&(p.clickTrackingParams=m);null!=f&&(p.locationInfo=g.qg(f));K7(c,"setPlaylist",p);e||I7(c,n);u8(a,new g.nB(1))},z8=function(a,b){if(b){var c=a.l.Db("captions","tracklist",{Bv:1});
c&&c.length?(a.l.zc("captions","track",b),a.G=!1):(a.l.fi("captions"),a.G=!0)}else a.l.zc("captions","track",{})},w8=function(a){return F7(a.g).videoId==a.l.getVideoData(1).videoId},u8=function(a,b){a.C.stop();
var c=a.H;if(!g.tB(c,b)){var d=g.U(b,2);d!=g.U(a.H,2)&&g.iI(a.l,d);a.H=b;A8(a.B,c,b)}},C8=function(a){g.O.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.nN()]},{D:"div",I:"ytp-remote-display-status-text",V:"{{statustext}}"}]}]});this.l=new g.YN(this,250);g.I(this,this.l);this.o=a;this.M(a,"presentingplayerstatechange",this.A);B8(this,g.eI(a))},B8=function(a,b){if(3==a.o.Ea()){var c={RECEIVER_NAME:a.o.Db("remote","currentReceiver").name};
c=g.U(b,128)?g.iM("$RECEIVER_NAME cihaz\u0131nda hata olu\u015ftu",c):g.uB(b)||g.U(b,4)?g.iM("$RECEIVER_NAME cihaz\u0131nda oynat\u0131l\u0131yor",c):g.iM("$RECEIVER_NAME cihaz\u0131na ba\u011flan\u0131ld\u0131",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},D8=function(a,b){g.RR.call(this,"Oynat\u0131lacak ekran se\u00e7in",0,a,b);
this.l=a;this.G={};this.M(a,"onMdxReceiversChange",this.J);this.M(a,"presentingplayerstatechange",this.J);this.J()},E8=function(a){g.OI.call(this,a);
this.l={key:S4(),name:"Bu bilgisayar"};this.A=null;this.B=[];this.J=this.g=null;this.H=[this.l];this.o=this.l;this.F=new g.nB(64);this.C=0;this.G=-1;if(!g.ly(g.V(this.player))){a=this.player;var b=g.ct(a);b&&(b=b.Im())&&(b=new D8(a,b),g.I(this,b));b=new C8(a);g.I(this,b);g.zI(a,b.element,4)}},A8=function(a,b,c){a.F=c;
a.player.P("presentingplayerstatechange",new g.zB(c,b))},F8=function(a,b){if(b.key!=a.o.key)if(b.key==a.l.key)l8();
else{a.o=b;var c=a.player.getPlaylistId();var d=a.player.getVideoData(1);var e=d.videoId;if(c||e){var f=a.player.We();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.za(l).videoId}else k=[e];f=a.player.ya(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Ph,index:Math.max(a.player.Ew(),0),currentTime:0==f?void 0:f};(d=I4(d))&&(c.locationInfo=d);d=c}else d=null;c8("Connecting to: "+g.qg(b));"cast-selector-receiver"==b.key?(e8(d||null),s7()?l7().setLaunchParams(d||
null):i7("setLaunchParams called before ready.")):!d&&o8()&&b8()==b.key?g.ir("yt-remote-connection-change",!0):(l8(),e8(d||null),d=a8().Kd(),(d=U4(d,b.key))&&m8(d,1))}},Hpa=/^https?$/i,Mqa=["POST",
"PUT"];g.B(G4,g.yf);g.h=G4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.H+"; newUri="+a);b=b?b.toUpperCase():"GET";this.H=a;this.B="";this.A=0;this.X=b;this.R=!1;this.l=!0;this.g=this.T?y4(this.T):y4(g.NW);this.O=this.T?x4(this.T):x4(g.NW);this.g.onreadystatechange=(0,g.z)(this.fv,this);try{t4(z4(this,"Opening Xhr")),this.Y=!0,this.g.open(b,String(a),!0),this.Y=!1}catch(f){t4(z4(this,"Error opening Xhr: "+f.message));D4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Epa(d,function(a,b){e.set(b,a)});
d=g.Ja(e.Id(),Fpa);c=g.v.FormData&&a instanceof g.v.FormData;!g.Ma(Mqa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.ea&&(this.g.responseType=this.ea);"withCredentials"in this.g&&this.g.withCredentials!==this.Z&&(this.g.withCredentials=this.Z);try{A4(this),0<this.C&&(this.L=Gpa(this.g),t4(z4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.z)(this.gv,this)):this.F=g.lg(this.gv,this.C,this)),t4(z4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){t4(z4(this,"Send error: "+f.message)),D4(this,f)}};
g.h.gv=function(){"undefined"!=typeof g.pW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,z4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(z4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),C4(this))};
g.h.U=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),C4(this,!0));G4.Aa.U.call(this)};
g.h.fv=function(){this.fa()||(this.Y||this.G||this.o?F4(this):this.gL())};
g.h.gL=function(){F4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<E4(this)?this.g.status:-1}catch(a){return-1}};
var C5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},B5={"'":"\\'"},Nqa={};g.h=J4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Ma(this.g,a)||g.Ma(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.yla)(b,a);0<=c?(g.Pa(b,c),b=!0):b=!1;return b||g.Qa(this.l,a)};
g.h.wc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Opa={nO:"atp",wQ:"ska",nQ:"que",PP:"mus",vQ:"sus",gP:"dsp"};L4.prototype.Bl=function(){var a=new L4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var d5,X4="",k5=f5("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",$pa=f5("loadCastFramework")||f5("loadCastApplicationFramework"),tqa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.B(n5,g.G);g.h=n5.prototype;g.h.KC=function(a){this.A=arguments;this.g=!1;this.Fa?this.o=(0,g.D)()+this.Vc:this.Fa=g.lg(this.B,this.Vc)};
g.h.stop=function(){this.Fa&&(g.v.clearTimeout(this.Fa),this.Fa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();n5.Aa.U.call(this)};
g.h.LC=function(){this.o?(this.Fa=g.lg(this.B,this.o-(0,g.D)()),this.o=null):(this.Fa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};o5.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
o5.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};g.h=p5.prototype;g.h.Rg=null;g.h.Ge=!1;g.h.Ji=null;g.h.As=null;g.h.xi=null;g.h.Lh=null;g.h.gg=null;g.h.ug=null;g.h.mh=null;g.h.oc=null;g.h.Jk=0;g.h.He=null;g.h.Ln=null;g.h.hg=null;g.h.vj=-1;g.h.Jz=!0;g.h.Ig=!1;g.h.lp=0;g.h.gn=null;var w5={},u5={};g.h=p5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.LM=function(a){a=a.target;var b=this.gn;b&&3==E4(a)?b.rj():this.TA(a)};
g.h.TA=function(a){try{if(a==this.oc)a:{var b=E4(this.oc),c=this.oc.A,d=this.oc.getStatus();if(g.rd&&!g.jc(10)||g.td&&!g.ic("420+")){if(4>b)break a}else if(3>b||3==b&&!g.kh&&!H4(this.oc))break a;this.Ig||4!=b||7==c||(8==c||0>=d?this.g.Ae(3):this.g.Ae(2));G5(this);var e=this.oc.getStatus();this.vj=e;var f=H4(this.oc);(this.Ge=200==e)?(4==b&&y5(this),this.B?(A5(this,b,f),g.kh&&this.Ge&&3==b&&(this.da.ga(this.l,"tick",this.IM),this.l.start())):x5(this,f),this.Ge&&!this.Ig&&(4==b?this.g.Wm(this):(this.Ge=
!1,t5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.hg=3,v5(13)):(this.hg=0,v5(14)),y5(this),z5(this))}}catch(k){this.oc&&H4(this.oc)}finally{}};
g.h.IM=function(){var a=E4(this.oc),b=H4(this.oc);this.Jk<b.length&&(G5(this),A5(this,a,b),this.Ge&&4!=a&&t5(this))};
g.h.bM=function(a){F5((0,g.z)(this.aM,this,a),0)};
g.h.aM=function(a){this.Ig||(G5(this),x5(this,a),t5(this))};
g.h.Sy=function(a){F5((0,g.z)(this.ZL,this,a),0)};
g.h.ZL=function(a){this.Ig||(y5(this),this.Ge=a,this.g.Wm(this),this.g.Ae(4))};
g.h.cancel=function(){this.Ig=!0;y5(this)};
g.h.mM=function(){this.Ji=null;var a=(0,g.D)();0<=a-this.As?(2!=this.Lh&&this.g.Ae(3),y5(this),this.hg=2,v5(18),z5(this)):E5(this,this.As-a)};g.h=K5.prototype;g.h.jp=null;g.h.Qd=null;g.h.hn=!1;g.h.ev=null;g.h.Il=null;g.h.Op=null;g.h.kp=null;g.h.be=null;g.h.vf=-1;g.h.uj=null;g.h.Qi=null;g.h.connect=function(a){this.kp=a;a=L5(this.g,null,this.kp);v5(3);this.ev=(0,g.D)();var b=this.g.G;null!=b?(this.uj=b[0],(this.Qi=b[1])?(this.be=1,M5(this)):(this.be=2,O5(this))):(v4(a,"MODE","init"),this.Qd=new p5(this,void 0,void 0,void 0),this.Qd.Rg=this.jp,s5(this.Qd,a,!1,null,!0),this.be=0)};
g.h.fC=function(a){if(a)this.be=2,O5(this);else{v5(4);var b=this.g;b.Ne=b.Xf.vf;h6(b,9)}a&&this.Ae(2)};
g.h.Io=function(a){return this.g.Io(a)};
g.h.abort=function(){this.Qd&&(this.Qd.cancel(),this.Qd=null);this.vf=-1};
g.h.dv=function(){return!1};
g.h.Ly=function(a,b){this.vf=a.vj;if(0==this.be)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Ne=this.vf;h6(c,2);return}this.uj=c[0];this.Qi=c[1]}else c=this.g,c.Ne=this.vf,h6(c,2);else if(2==this.be)if(this.hn)v5(7),this.Op=(0,g.D)();else if("11111"==b){if(v5(6),this.hn=!0,this.Il=(0,g.D)(),c=this.Il-this.ev,!g.rd||g.jc(10)||500>c)this.vf=200,this.Qd.cancel(),v5(12),N5(this.g,this,!0)}else v5(8),this.Il=this.Op=(0,g.D)(),this.hn=!1};
g.h.Wm=function(){this.vf=this.Qd.vj;if(this.Qd.Ge)0==this.be?this.Qi?(this.be=1,M5(this)):(this.be=2,O5(this)):2==this.be&&((!g.rd||g.jc(10)?!this.hn:200>this.Op-this.Il)?(v5(11),N5(this.g,this,!1)):(v5(12),N5(this.g,this,!0)));else{0==this.be?v5(9):2==this.be&&v5(10);var a=this.g;a.Ne=this.vf;h6(a,2)}};
g.h.Ak=function(){return this.g.Ak()};
g.h.isActive=function(){return this.g.isActive()};
g.h.Ae=function(a){this.g.Ae(a)};g.h=P5.prototype;g.h.dj=null;g.h.yd=null;g.h.Sb=null;g.h.ip=null;g.h.Ml=null;g.h.Lt=null;g.h.Ul=null;g.h.lk=0;g.h.mI=0;g.h.Tc=null;g.h.dg=null;g.h.jf=null;g.h.Lg=null;g.h.Xf=null;g.h.Jn=null;g.h.Wh=-1;g.h.Qv=-1;g.h.Ne=-1;g.h.Hh=0;g.h.Ch=0;g.h.Jg=8;var i6=new g.yf;g.B(Q5,g.$e);g.B(R5,g.$e);g.B(S5,g.$e);g.h=P5.prototype;g.h.connect=function(a,b,c,d,e){v5(0);this.ip=b;this.dj=c||{};d&&g.sa(e)&&(this.dj.OSID=d,this.dj.OAID=e);this.C?(F5((0,g.z)(this.du,this,a),100),Y5(this)):this.du(a)};
g.h.du=function(a){this.Xf=new K5(this);this.Xf.jp=null;this.Xf.l=this.B;this.Xf.connect(a)};
g.h.dv=function(){return 0==this.g};
g.h.Qy=function(a){this.dg=null;c6(this,a)};
g.h.Py=function(){this.jf=null;this.Sb=new p5(this,this.o,"rpc",this.F);this.Sb.Rg=null;this.Sb.lp=0;var a=this.Lt.clone();g.Cm(a,"RID","rpc");g.Cm(a,"SID",this.o);g.Cm(a,"CI",this.Jn?"0":"1");g.Cm(a,"AID",this.Wh);U5(this,a);if(!g.rd||g.jc(10))g.Cm(a,"TYPE","xmlhttp"),s5(this.Sb,a,!0,this.Ul,!1);else{g.Cm(a,"TYPE","html");var b=this.Sb,c=!!this.Ul;b.Lh=3;b.gg=u4(a.clone());D5(b,c)}};
g.h.Ly=function(a,b){if(0!=this.g&&(this.Sb==a||this.yd==a))if(this.Ne=a.vj,this.yd==a&&3==this.g)if(7<this.Jg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.jf){if(this.Sb)if(this.Sb.xi+3E3<this.yd.xi)Z5(this),this.Sb.cancel(),this.Sb=null;else break a;f6(this);v5(19)}}else this.Qv=c[1],0<this.Qv-this.Wh&&37500>c[2]&&this.Jn&&0==this.Ch&&!this.Lg&&(this.Lg=F5((0,g.z)(this.QI,this),6E3));else h6(this,11)}else b!=Nqa.MO.g&&h6(this,11);else if(this.Sb==a&&
Z5(this),!g.ib(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Wh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Ul=e[2],e=e[3],null!=e?this.Jg=e:this.Jg=6,this.g=3,this.Tc&&this.Tc.Ut(),this.Lt=L5(this,this.Ak()?this.Ul:null,this.ip),d6(this)):"stop"==e[0]&&h6(this,7):3==this.g&&("stop"==e[0]?h6(this,7):"noop"!=e[0]&&this.Tc&&this.Tc.Tt(e),this.Ch=0)}}};
g.h.QI=function(){null!=this.Lg&&(this.Lg=null,this.Sb.cancel(),this.Sb=null,f6(this),v5(20))};
g.h.Wm=function(a){if(this.Sb==a){Z5(this);this.Sb=null;var b=2}else if(this.yd==a)this.yd=null,b=1;else return;this.Ne=a.vj;if(0!=this.g)if(a.Ge)1==b?(b=(0,g.D)()-a.xi,i6.dispatchEvent(new R5(i6,a.mh?a.mh.length:0,b,this.Hh)),X5(this),this.A.length=0):d6(this);else{var c=a.hg,d;if(!(d=3==c||7==c||0==c&&0<this.Ne)){if(d=1==b)this.yd||this.dg||1==this.g||2<=this.Hh?d=!1:(this.dg=F5((0,g.z)(this.Qy,this,a),e6(this,this.Hh)),this.Hh++,d=!0);d=!(d||2==b&&f6(this))}if(d)switch(c){case 1:h6(this,5);break;
case 4:h6(this,10);break;case 3:h6(this,6);break;case 7:h6(this,12);break;default:h6(this,2)}}};
g.h.tC=function(a){if(!g.Ma(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.mN=function(a){a?v5(2):(v5(1),g6(this,8))};
g.h.Io=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new G4;a.Z=!1;return a};
g.h.isActive=function(){return!!this.Tc&&this.Tc.isActive(this)};
g.h.Ae=function(a){i6.dispatchEvent(new S5(i6,a))};
g.h.Ak=function(){return!(!g.rd||g.jc(10))};
g.h=j6.prototype;g.h.Ut=function(){};
g.h.Tt=function(){};
g.h.St=function(){};
g.h.zo=function(){};
g.h.Mu=function(){return{}};
g.h.isActive=function(){return!0};g.B(k6,g.G);g.h=k6.prototype;g.h.UL=function(){this.Vc=Math.min(3E5,2*this.Vc);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Vc+15E3*Math.random();g.In(this.g,a);this.l=(0,g.D)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Vc=5E3};g.B(l6,j6);g.h=l6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Dc=function(a){return this.o.Dc(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.J||(this.J=!0,g.Ye(this.o),m6(this),g.Ye(this.l),this.l=null)};
g.h.fa=function(){return this.J};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new P5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.O),e=this.g;e&&(e.Tc=null);d.Tc=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Wh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Yb(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):n6(this)&&$5(this.g,c)};
g.h.Ut=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)$5(this.g,a[b])}this.P("handlerOpened")};
g.h.St=function(a){var b=2==a&&401==this.g.Ne;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.zo=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Mu=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.Yb(a,this.B);return a};
g.h.Tt=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),W5(this.g)):this.P("handlerMessage",new eqa(a[0],a[1]))};
g.h.JN=function(){this.l.isActive();var a=this.g,b=0;a.Sb&&b++;a.yd&&b++;0!=b||this.connect(this.B,this.A)};o6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
o6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
o6.prototype.B=function(a){a(Error("request timed out"))};var kqa=(0,g.D)(),t6=null,x6=Array(50),w6=-1,y6=!1;g.B(z6,g.N);z6.prototype.Kd=function(){return this.g};
z6.prototype.contains=function(a){return!!T4(this.g,a)};
z6.prototype.get=function(a){return a?U4(this.g,a):null};
z6.prototype.info=function(a){v6(this.F,a)};g.B(B6,g.N);var G8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=B6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Fa)&&this.ZA()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Fa)||(g.qp(this.Fa),this.Fa=window.NaN)};
g.h.U=function(){this.stop();B6.Aa.U.call(this)};
g.h.ZA=function(){this.Fa=window.NaN;this.g=g.Fp(p6(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.z)(this.LN,this),onError:(0,g.z)(this.KN,this),sd:(0,g.z)(this.MN,this)})};
g.h.LN=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new M4(c))};
g.h.KN=function(a){this.g=null;a.status&&404==a.status?this.l>=G8.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=G8[this.l],this.Fa=g.op((0,g.z)(this.ZA,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.MN=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.B(D6,z6);g.h=D6.prototype;g.h.start=function(){C6(this)&&this.P("screenChange");!g.qs("yt-remote-lounge-token-expiration")&&E6(this);g.qp(this.l);this.l=g.op((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){C6(this);A6(this,a);F6(this,!1);this.P("screenChange");b(a);a.token||E6(this)};
g.h.remove=function(a,b){var c=C6(this);mqa(this,a)&&(F6(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Fn=function(a,b,c,d){var e=C6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,F6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.qp(this.l);D6.Aa.U.call(this)};
g.h.UC=function(a){C6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}F6(this,!b);b&&v6(this.F,"Missed "+b+" lounge tokens.")};
g.h.TC=function(a){v6(this.F,"Requesting lounge tokens failed: "+a)};g.B(H6,g.N);g.h=H6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.qs("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.D)()-144E5<a?0:a)?K6(this):(this.A=(0,g.D)()+3E5,g.ps("yt-remote-fast-check-period",this.A),this.Gr())};
g.h.isEmpty=function(){return g.Qb(this.g)};
g.h.update=function(){G6("Updating availability on schedule.");var a=this.C(),b=g.Db(this.g,function(b,d){return b&&!!U4(a,d)},this);
J6(this,b)};
g.h.U=function(){g.qp(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);H6.Aa.U.call(this)};
g.h.Gr=function(){g.qp(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=L6(this);if(g.Hb(a)){var b=p6(this.B,"/pairing/get_screen_availability");this.l=q6(this.B,b,{lounge_token:g.Kb(a).join(",")},(0,g.z)(this.BL,this,a),(0,g.z)(this.AL,this))}else J6(this,{}),K6(this)};
g.h.BL=function(a,b){this.l=null;var c=g.Kb(L6(this));if(g.cb(c,g.Kb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;J6(this,d);K6(this)}else this.Ib("Changing Screen set during request."),this.Gr()};
g.h.AL=function(a){this.Ib("Screen availability failed: "+a);this.l=null;K6(this)};
g.h.Ib=function(a){v6("OnlineScreenService",a)};g.B(M6,z6);g.h=M6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Fn=function(a,b,c,d){this.o.contains(a)?this.o.Fn(a,b,c,d):(a="Updating name of unknown screen: "+a.name,v6(this.F,a),d(Error(a)))};
g.h.Kd=function(a){return a?this.g:g.Sa(this.g,(0,g.Dd)(this.A,function(a){return!this.contains(a)},this))};
g.h.aB=function(){return(0,g.Dd)(this.Kd(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.bB=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new B6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ye(f);d(N6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ye(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.ON=function(a,b,c,d){g.Fp(p6(this.C,"/pairing/get_screen"),{method:"POST",tb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.z)(function(a,d){var e=new M4(d.screen||{});if(!e.name||P6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);P6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(N6(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
sd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Ye(this.o);g.Ye(this.l);M6.Aa.U.call(this)};
g.h.eD=function(){Q6(this);this.P("screenChange");this.l.update()};
M6.prototype.dispose=M6.prototype.dispose;g.B(S6,g.N);g.h=S6.prototype;g.h.Xm=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.Od=function(a){this.fa()||(a&&T6(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){v6(this.O,a)};
g.h.dB=function(){return null};
g.h.Pr=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){T6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Pr("");S6.Aa.U.call(this)};g.B(V6,S6);g.h=V6.prototype;g.h.Or=function(a){if(this.g){if(this.g==a)return;T6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);qqa(this)};
g.h.Xh=function(a){this.info("launchWithParams no-op for Cast: "+g.qg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.Od()},this),(0,g.z)(function(){this.Od(Error("Failed to stop receiver app."))},this)):this.Od(Error("Stopping cast device witout session."))};
g.h.Pr=g.va;g.h.U=function(){this.info("disposeInternal");g.qp(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;V6.Aa.U.call(this)};
g.h.xM=function(a,b){if(!this.fa())if(b){var c=g.Tn(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.qg(c));switch(d){case "mdxSessionStatus":U6(this,c.screenId);break;default:T6(this,"Unknown youtube message: "+d)}}else T6(this,"Unable to parse message.")}else T6(this,"No data in message.")};
g.h.Vu=function(a,b,c,d){O6(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(T6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.op((0,g.z)(this.Vu,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.dB=function(){return this.g};
g.h.PN=function(a){this.fa()||a||(T6(this,"Cast session died."),this.Od())};g.B(W6,S6);g.h=W6.prototype;g.h.Or=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.Xh=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.va;g.qp(this.C);this.A?this.A.stop((0,g.z)(this.Od,this,null),(0,g.z)(this.Od,this,"Failed to stop DIAL device.")):this.Od()};
g.h.U=function(){this.g();this.g=g.va;g.qp(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;W6.Aa.U.call(this)};
g.h.SN=function(a){this.fa()||a||(T6(this,"DIAL session died."),this.g(),this.g=g.va,this.Od())};
g.h.yp=function(a){this.J=S4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,Y6(this));a(b);X6(this)}else this.F=(0,g.z)(function(){g.qp(this.C);this.F=g.va;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,Y6(this));a(b);X6(this)},this),this.C=g.op((0,g.z)(function(){this.F()},this),100)};
g.h.AD=function(a,b,c){O6(this.H,this.G.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Xm(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.yp(b,c)},this),(0,g.z)(function(a){T6(this,"Failed to get DIAL screen: "+a);
this.yp(b,c)},this))};g.B(Z6,S6);Z6.prototype.stop=function(){this.Od()};
Z6.prototype.Or=g.va;Z6.prototype.Xh=function(){g.qp(this.g);this.g=window.NaN;var a=U4(this.H.Kd(),this.l.label);a?this.Xm(a):this.Od(Error("No such screen"))};
Z6.prototype.U=function(){g.qp(this.g);this.g=window.NaN;Z6.Aa.U.call(this)};g.B($6,g.N);g.h=$6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.Ny,this),(0,g.z)(this.lL,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.sJ,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.fa()||(window.chrome.cast.addReceiverActionListener(this.A),hqa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.cB,this)),this.o=e7(this),window.chrome.cast.setCustomReceivers(this.o,g.va,(0,g.z)(function(a){this.Ib("Failed to set initial custom receivers: "+g.qg(a))},this)),this.P("yt-remote-cast2-availability-change",c7(this)),b(!0))},this),(0,g.z)(function(a){this.Ib("Failed to initialize API: "+g.qg(a));
b(!1)},this))};
g.h.dN=function(a,b){b7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)b7("Unsetting old screen status: "+this.g.l.friendlyName),d7(this,null)}if(a&&b){if(!this.g){c=U4(this.l.Kd(),a);if(!c){b7("setConnectedScreenStatus: Unknown screen.");return}var d=a7(this,c);d||(b7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.va,(0,g.z)(function(a){this.Ib("Failed to set initial custom receivers: "+g.qg(a))},this)));
b7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);d7(this,new Z6(this.l,d),!0)}this.g.Pr(b)}else b7("setConnectedScreenStatus: no screen.")};
g.h.eN=function(a){this.fa()?this.Ib("Setting connection data on disposed cast v2"):this.g?this.g.Xh(a):this.Ib("Setting connection data without a session")};
g.h.RN=function(){this.fa()?this.Ib("Stopping session on disposed cast v2"):this.g?(this.g.stop(),d7(this,null)):b7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.Ny,this),(0,g.z)(this.GL,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.cB,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Qa(g.y("yt.mdx.remote.debug.handlers_")||[],r6);g.Ye(this.g);$6.Aa.U.call(this)};
g.h.Ib=function(a){v6("Controller",a)};
g.h.Oy=function(a,b){this.g==a&&(b||d7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.hL=function(a,b){if(!this.fa())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),b7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)b7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{b7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:d7(this,
new Z6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:d7(this,new W6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:d7(this,new V6(this.l,a));break;default:this.Ib("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Ib("Stopping receiver w/o session: "+a.friendlyName)}else this.Ib("onReceiverAction_ called without receiver.")};
g.h.sJ=function(a){if(this.fa())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Ib("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Ib("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return b7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Ib('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);d7(this,new W6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.AD,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.yp,b))};
g.h.Ny=function(a){if(!this.fa()){b7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)b7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),d7(this,new V6(this.l,b),!0);else{this.Ib("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=U4(this.l.Kd(),c.label);
d&&N4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(b7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ye(this.g),this.g=new V6(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.Oy,this,this.g)),this.g.Xh(null));this.g.Or(a)}}};
g.h.QN=function(){return this.g?this.g.dB():null};
g.h.GL=function(a){this.fa()||(this.Ib("Failed to estabilish a session: "+g.qg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&d7(this,null))};
g.h.lL=function(a){b7("Receiver availability updated: "+a);if(!this.fa()){var b=c7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;c7(this)!=b&&this.P("yt-remote-cast2-availability-change",c7(this))}};
g.h.cB=function(){this.fa()||(this.o=e7(this),b7("Updating custom receivers: "+g.qg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.va,(0,g.z)(function(){this.Ib("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",c7(this)))};
$6.prototype.setLaunchParams=$6.prototype.eN;$6.prototype.setConnectedScreenStatus=$6.prototype.dN;$6.prototype.stopSession=$6.prototype.RN;$6.prototype.getCastSession=$6.prototype.QN;$6.prototype.requestSession=$6.prototype.requestSession;$6.prototype.init=$6.prototype.init;$6.prototype.dispose=$6.prototype.dispose;var n7=[];v7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";w7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.g=a.trackData,this.Pe=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.C=a.playerTimeAt,this.A=a.seekableStart,this.l=a.seekableEnd,this.G=a.duration,this.H=a.loadedTime,this.o=a.liveIngestionTime,this.B=
!(0,window.isNaN)(this.o))};
v7.prototype.isAdPlaying=function(){return 1081==this.playerState};
v7.prototype.clone=function(){return new v7(B7(this))};g.B(E7,g.N);g.h=E7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.va,M7(this,"play")):K7(this,"play"),J7(this,1,z7(F7(this))),this.P("remotePlayerChange")):H7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.va,M7(this,"pause")):K7(this,"pause"),J7(this,2,z7(F7(this))),this.P("remotePlayerChange")):H7(this,this.pause)};
g.h.YA=function(a){if(1==this.g){if(this.l){var b=F7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.playerState||3==b.playerState?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.va,M7(this,"seekTo",{newTime:a}))}else K7(this,"seekTo",{newTime:a});J7(this,3,a);this.P("remotePlayerChange")}else H7(this,g.Ea(this.YA,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.va,M7(this,"stopVideo")):K7(this,"stopVideo");var a=F7(this);a.index=-1;a.videoId="";w7(a);I7(this,a);this.P("remotePlayerChange")}else H7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=F7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){v6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.Ib("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){v6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.Ib("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);K7(this,"setVolume",e)}c.muted=b;c.volume=a;I7(this,c)}else H7(this,g.Ea(this.setVolume,a,b))};
g.h.Xz=function(a,b){if(1==this.g){var c=F7(this),d={videoId:a};b&&(c.g={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.qg(b.style),g.Yb(d,c.g));K7(this,"setSubtitlesTrack",d);I7(this,c)}else H7(this,g.Ea(this.Xz,a,b))};
g.h.Cs=function(a,b){if(1==this.g){K7(this,"setAudioTrack",{videoId:a,audioTrackId:b.kb.id});var c=F7(this);c.audioTrackId=b.kb.id;I7(this,c)}else H7(this,g.Ea(this.Cs,a,b))};
g.h.XA=function(a,b){if(1==this.g){if(a&&b){var c=F7(this);A7(c,a,b);I7(this,c)}K7(this,"previous")}else H7(this,g.Ea(this.XA,a,b))};
g.h.WA=function(a,b){if(1==this.g){if(a&&b){var c=F7(this);A7(c,a,b);I7(this,c)}K7(this,"next")}else H7(this,g.Ea(this.WA,a,b))};
g.h.uu=function(){1==this.g?K7(this,"dismissAutoplay"):H7(this,this.uu)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}E7.Aa.dispose.call(this)};
g.h.U=function(){G7(this);this.A=null;this.B.clear();D7(this,null);E7.Aa.U.call(this)};
g.h.Ds=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.dL=function(a,b){this.P(a,b)};
g.h.WI=function(a){if(!a)this.mk(null),D7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=F7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)v6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,I7(this,b)}};
g.h.mk=function(a){v6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),L7(this),this.P("remotePlayerChange")};
g.h.VI=function(a){a?(L7(this),this.P("remotePlayerChange")):this.mk(null)};
g.h.jJ=function(){var a=r7();a&&D7(this,a)};
g.h.Ib=function(a){v6("CP",a)};g.B(N7,g.N);g.h=N7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;g.sa(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.sa(k)&&(l.currentIndex=k);c&&(this.Sa.listId=c);this.Sa.videoId=d;this.Sa.index=k||0;this.Sa.state=3;y7(this.Sa,m);this.A="UNSUPPORTED";O7("Connecting with setPlaylist and params: "+g.qg(l));this.g.connect({method:"setPlaylist",
params:g.qg(l)},a,$4())}else O7("Connecting without params"),this.g.connect({},a,$4());xqa(this)};
g.h.dispose=function(){this.fa()||(this.P("beforeDispose"),P7(this,3));N7.Aa.dispose.call(this)};
g.h.U=function(){Q7(this);S7(this);R7(this);g.qp(this.H);this.H=window.NaN;g.qp(this.J);this.J=window.NaN;this.o=null;g.Eq(this.R);this.R.length=0;this.g.dispose();N7.Aa.U.call(this);this.A=this.F=this.l=this.Sa=this.g=null};
g.h.NC=function(){this.C(2)};
g.h.aJ=function(){O7("Channel opened");this.T&&(this.T=!1,R7(this),this.O=g.op((0,g.z)(function(){O7("Timing out waiting for a screen.");this.C(1)},this),15E3));
Upa(fqa(this.g),this.Y)};
g.h.XI=function(){O7("Channel closed");(0,window.isNaN)(this.B)?c5(!0):c5();this.dispose()};
g.h.YI=function(a){c5();(0,window.isNaN)(this.G())?(O7("Channel error: "+a+" without reconnection"),this.dispose()):(this.T=!0,O7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),P7(this,2))};
g.h.ZI=function(a){a.params?O7("Received: action="+a.action+", params="+g.qg(a.params)):O7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Tn(a.params.devices);this.l=(0,g.E)(a,function(a){return new L4(a)});
a=!!g.Ja(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
V7(this,a);break;case "loungeScreenDisconnected":g.Ra(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
V7(this,!1);break;case "remoteConnected":var b=new L4(g.Tn(a.params.device));g.Ja(this.l,function(a){return b?a.id==b.id:!1})||g.Oa(this.l,b);
break;case "remoteDisconnected":b=new L4(g.Tn(a.params.device));g.Ra(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":W7(this,a);break;case "nowPlaying":Aqa(this,a);break;case "onStateChange":X7(this,a);break;case "onAdStateChange":Bqa(this,a);break;case "onVolumeChanged":Cqa(this,a);break;case "onSubtitlesTrackChanged":zqa(this,a);break;case "nowAutoplaying":Dqa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.P("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":Eqa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:O7("Unrecognized action: "+a.action)}};
g.h.SM=function(){if(this.o){var a=this.o;this.o=null;this.Sa.videoId!=a&&T7(this,"getNowPlaying")}};
N7.prototype.subscribe=N7.prototype.subscribe;N7.prototype.unsubscribeByKey=N7.prototype.Dc;N7.prototype.ca=function(){var a=3;this.fa()||(a=0,(0,window.isNaN)(this.G())?n6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
N7.prototype.getProxyState=N7.prototype.ca;N7.prototype.C=function(a){O7("Disconnecting with "+a);Q7(this);this.P("beforeDisconnect",a);1==a&&c5();m6(this.g,a);this.dispose()};
N7.prototype.disconnect=N7.prototype.C;N7.prototype.ba=function(){var a=this.Sa;this.o&&(a=this.Sa.clone(),A7(a,this.o,a.index));return B7(a)};
N7.prototype.getPlayerContextData=N7.prototype.ba;
N7.prototype.na=function(a){var b=new v7(a);b.videoId&&b.videoId!=this.Sa.videoId&&(this.o=b.videoId,g.qp(this.H),this.H=g.op((0,g.z)(this.SM,this),5E3));var c=[];this.Sa.listId==b.listId&&this.Sa.videoId==b.videoId&&this.Sa.index==b.index||c.push("remoteQueueChange");this.Sa.playerState==b.playerState&&this.Sa.volume==b.volume&&this.Sa.muted==b.muted&&z7(this.Sa)==z7(b)&&g.qg(this.Sa.g)==g.qg(b.g)||c.push("remotePlayerChange");this.Sa.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
N7.prototype.setPlayerContextData=N7.prototype.na;N7.prototype.Z=function(){var a=this.g.C.id,b=g.Ja(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
N7.prototype.getOtherConnectedRemoteId=N7.prototype.Z;N7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.D)():window.NaN};
N7.prototype.getReconnectTimeout=N7.prototype.G;N7.prototype.X=function(){return this.A||"UNSUPPORTED"};
N7.prototype.getAutoplayMode=N7.prototype.X;N7.prototype.ea=function(){return this.F||""};
N7.prototype.getAutoplayVideoId=N7.prototype.ea;N7.prototype.ra=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.Jn(a.g);a.start()}};
N7.prototype.reconnect=N7.prototype.ra;N7.prototype.ha=function(a,b){T7(this,a,b);U7(this)};
N7.prototype.sendMessage=N7.prototype.ha;g.B(Y7,z6);g.h=Y7.prototype;g.h.Kd=function(a){return this.Kc.$_gs(a)};
g.h.contains=function(a){return!!this.Kc.$_c(a)};
g.h.get=function(a){return this.Kc.$_g(a)};
g.h.start=function(){this.Kc.$_st()};
g.h.add=function(a,b,c){this.Kc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Kc.$_r(a,b,c)};
g.h.Fn=function(a,b,c,d){this.Kc.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.Kc.$_ubk(this.l[a]);this.l.length=0;this.Kc=null;Y7.Aa.U.call(this)};
g.h.NN=function(){this.P("screenChange")};
g.h.GK=function(){this.P("onlineScreenChange")};
M6.prototype.$_st=M6.prototype.start;M6.prototype.$_gspc=M6.prototype.ON;M6.prototype.$_gsppc=M6.prototype.bB;M6.prototype.$_c=M6.prototype.contains;M6.prototype.$_g=M6.prototype.get;M6.prototype.$_a=M6.prototype.add;M6.prototype.$_un=M6.prototype.Fn;M6.prototype.$_r=M6.prototype.remove;M6.prototype.$_gs=M6.prototype.Kd;M6.prototype.$_gos=M6.prototype.aB;M6.prototype.$_s=M6.prototype.subscribe;M6.prototype.$_ubk=M6.prototype.Dc;var Z7=null,$7=null,p8=null,d8=[];g.r(s8,g.G);g.h=s8.prototype;
g.h.U=function(){g.G.prototype.U.call(this);this.A.stop();this.C.stop();this.L.stop();this.T();this.g.unsubscribe("proxyStateChange",this.Ky,this);this.g.unsubscribe("remotePlayerChange",this.pk,this);this.g.unsubscribe("remoteQueueChange",this.Ym,this);this.g.unsubscribe("autoplayUpNext",this.ky,this);this.g.unsubscribe("previousNextChange",this.Hy,this);this.g.unsubscribe("nowAutoplaying",this.Dy,this);this.g.unsubscribe("autoplayDismissed",this.jy,this);this.g=this.B=null};
g.h.Zw=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(w8(this)){if(!F7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==F7(this.g).playerState?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.J.rj(c[0],c[1]);break;case "control_subtitles_set_track":x8(this,c[0]);break;case "control_set_audio_track":c=c[0],w8(this)&&this.g.Cs(this.l.getVideoData(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.ya();y8(this,0==c?void 0:c);break;case "control_seek":y8(this,c[0]);break;case "control_subtitles_set_track":x8(this,c[0]);break;case "control_set_audio_track":c=c[0],w8(this)&&this.g.Cs(this.l.getVideoData(1).videoId,c)}};
g.h.UI=function(a){this.L.KC(a)};
g.h.uN=function(a){this.Zw("control_subtitles_set_track",g.Qb(a)?null:a)};
g.h.kA=function(){var a=this.l.Db("captions","track");g.Qb(a)||x8(this,a)};
g.h.zy=function(a){if(w8(this)){this.g.unsubscribe("remotePlayerChange",this.pk,this);var b=Math.round(a.volume);a=!!a.muted;var c=F7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.O.start();this.g.subscribe("remotePlayerChange",this.pk,this)}};
g.h.ZJ=function(){g.Qb(this.F)||z8(this,this.F);this.G=!1};
g.h.Ky=function(a,b){this.C.stop();2==b&&this.iA()};
g.h.pk=function(){if(w8(this)){this.A.stop();var a=F7(this.g);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.B.G=1;break;case 1082:case 1083:this.B.G=0;break;default:this.B.G=-1}switch(a.playerState){case 1081:case 1:u8(this,new g.nB(8));this.hA();break;case 1085:case 3:u8(this,new g.nB(9));break;case 1083:case 0:u8(this,new g.nB(2));this.J.stop();t8(this,this.l.getVideoData().lengthSeconds);break;case 1084:u8(this,new g.nB(4));break;case 2:u8(this,new g.nB(4));t8(this,z7(a));
break;case -1:u8(this,new g.nB(64));break;case -1E3:u8(this,new g.nB(128,{errorCode:"mdx.remoteerror",message:"Bu video uzaktan oynatma i\u00e7in uygun de\u011fil."}))}a=F7(this.g).g;var b=this.F;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.F=a,z8(this,a));a=F7(this.g);-1==a.volume||Math.round(this.l.Kb())==a.volume&&this.l.isMuted()==a.muted||this.O.isActive()||this.KA()}else v8(this)};
g.h.Hy=function(){this.l.P("mdxpreviousnextchange")};
g.h.Ym=function(){w8(this)||v8(this)};
g.h.eC=function(){this.g.uu()};
g.h.ky=function(a){a&&(a=g.Fp("/watch_queue_ajax",{method:"GET",Ec:{action_get_watch_queue_item:1,video_id:a},onSuccess:(0,g.z)(this.fM,this)}))&&(this.T=(0,g.z)(a.abort,a))};
g.h.fM=function(a,b){var c=new g.cA(g.V(this.l),{videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.Dy=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.jy=function(){this.l.P("mdxautoplaycanceled")};
g.h.EG=function(a,b){-1==F7(this.g).playerState?y8(this,a):b&&this.g.YA(a)};
g.h.KA=function(){if(w8(this)){var a=F7(this.g);this.o.Pa(this.R);a.muted?this.l.mute():this.l.Xe();this.l.setVolume(a.volume);this.R=this.o.M(this.l,"onVolumeChange",this.zy)}};
g.h.hA=function(){this.A.stop();if(!this.g.fa()){var a=F7(this.g);1==a.playerState&&u8(this,new g.nB(8));t8(this,z7(a));this.A.start()}};
g.h.iA=function(){this.C.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.C.start()};g.r(C8,g.O);C8.prototype.A=function(a){B8(this,a.state)};g.r(D8,g.RR);D8.prototype.J=function(){var a=this.l.Db("remote","receivers");a&&1<a.length&&!this.l.Db("remote","quickCast")?(this.G=g.eb(a,this.B,this),g.SR(this,(0,g.E)(a,this.B)),a=this.l.Db("remote","currentReceiver"),this.ze(this.B(a)),this.enable(!0)):this.enable(!1)};
D8.prototype.B=function(a){return a.key};
D8.prototype.ye=function(a){return"cast-selector-receiver"==a?"Yay\u0131nla...":this.G[a].name};
D8.prototype.Zc=function(a){g.RR.prototype.Zc.call(this,a);this.l.zc("remote","currentReceiver",this.G[a]);this.A.rb()};g.r(E8,g.OI);g.h=E8.prototype;g.h.create=function(){Jqa(g.cy(g.V(this.player)));this.B.push(g.er("yt-remote-before-disconnect",this.RI,this));this.B.push(g.er("yt-remote-connection-change",this.mL,this));this.B.push(g.er("yt-remote-receiver-availability-change",this.Iy,this));this.B.push(g.er("yt-remote-auto-connect",this.kL,this));this.B.push(g.er("yt-remote-receiver-resumed",this.jL,this));this.Iy()};
g.h.load=function(){this.player.oq();g.OI.prototype.load.call(this);this.A=new s8(this,this.player,this.g);var a=(a=r8())?a.currentTime:0;var b=o8()?new E7(j8(),void 0):null;0==a&&b&&(a=z7(F7(b)));0!=a&&(this.C=a||0,this.player.P("progresssync",a,void 0));A8(this,this.F,this.F);g.yV(this.player.app,6)};
g.h.unload=function(){this.player.P("mdxautoplaycanceled");this.o=this.l;g.Ze(this.A,this.g);this.g=this.A=null;g.OI.prototype.unload.call(this);g.yV(this.player.app,5)};
g.h.U=function(){g.fr(this.B);g.OI.prototype.U.call(this)};
g.h.ak=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.A.Zw.apply(this.A,[a].concat(g.ea(c)))};
g.h.HC=function(){return this.loaded?this.A.suggestion:null};
g.h.Pe=function(){return this.g?F7(this.g).Pe:!1};
g.h.hasNext=function(){return this.g?F7(this.g).hasNext:!1};
g.h.qG=function(){var a=F7(this.g),b=this.player.getVideoData();return{allowSeeking:g.Q(g.V(this.player).experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.dc():!a.isAdPlaying()&&this.player.dc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.C,displayedStart:-1,duration:a.B?a.G+x7(a):a.G,ingestionTime:a.B?a.o+x7(a):a.o,isPeggedToLive:1>=(a.B?a.l+x7(a):a.l)-this.C,loaded:a.H,seekableEnd:a.B?a.l+x7(a):a.l,seekableStart:0<a.A?a.A+x7(a):a.A}};
g.h.rG=function(){this.g&&this.g.WA()};
g.h.sG=function(){this.g&&this.g.XA()};
g.h.RI=function(a){1==a&&(this.J=this.g?F7(this.g):null)};
g.h.mL=function(){var a=o8()?new E7(j8(),void 0):null;if(a){var b=this.o;this.loaded&&this.unload();this.g=a;this.J=null;b.key!=this.l.key&&(this.o=b,this.load())}else g.Ye(this.g),this.g=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.player.getVideoData().videoId&&this.player.Cw(a.videoId,z7(a)));this.player.P("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.Iy=function(){this.H=[this.l].concat(Kqa());var a=k8()||this.l;F8(this,a);this.player.ma("onMdxReceiversChange")};
g.h.kL=function(){var a=k8();F8(this,a)};
g.h.jL=function(){this.o=k8()};
g.h.pG=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.H;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?t7():F8(this,b)),this.loaded?this.o:this.l;case "quickCast":return 2==this.H.length&&"cast-selector-receiver"==this.H[1].key?(b&&t7(),!0):!1}};
g.h.tG=function(){K7(this.g,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Rb=function(){return!1};g.bQ.remote=E8;})(_yt_player);
